{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationFailed"}]}]}],"sections":[],"metadata":{"role":"symbol","title":"MBSCipherError.Code.authenticationFailed","roleHeading":"Case","externalID":"c:@E@MBSCipherError@MBSCipherErrorAuthenticationFailed","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"authenticationFailed","kind":"identifier"}],"modules":[{"name":"MbSecureCrypto"}],"platforms":[{"name":"iOS","introducedAt":"15.6","unavailable":false,"beta":false,"deprecated":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"15.6"},{"beta":false,"introducedAt":"15.6","name":"Mac Catalyst","deprecated":false,"unavailable":false}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorAuthenticationFailed"}]},"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/authenticationFailed","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/authenticationfailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/authenticationfailed"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/authenticationFailed":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorAuthenticationFailed"}],"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/authenticationfailed","title":"MBSCipherError.Code.authenticationFailed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"authenticationFailed","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/authenticationFailed"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","type":"topic","title":"MBSCipherError.Code","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","abstract":[{"type":"text","text":"Error codes for cipher operations"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","title":"MbSecureCrypto","role":"collection","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MBSCipherErrorAuthenticationFailed","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MBSCipherErrorAuthenticationFailed","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MBSCipherErrorAuthenticationFailed"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1authenticationFailed\/title","op":"replace","value":"MBSCipherErrorAuthenticationFailed"},{"value":[{"text":"MBSCipherErrorAuthenticationFailed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1authenticationFailed\/fragments"},{"op":"replace","value":"MBSCipherError","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title"},{"op":"replace","value":[{"text":"MBSCipherError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments"},{"value":[{"text":"MBSCipherError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle"}]}]}