{"metadata":{"symbolKind":"case","modules":[{"name":"MbSecureCrypto"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorUnsupportedAlgorithm"}],"platforms":[{"beta":false,"introducedAt":"15.6","deprecated":false,"name":"iOS","unavailable":false},{"introducedAt":"15.6","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"15.6","unavailable":false}],"title":"MBSCipherError.Code.unsupportedAlgorithm","externalID":"c:@E@MBSCipherError@MBSCipherErrorUnsupportedAlgorithm","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unsupportedAlgorithm"}]},"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/unsupportedAlgorithm","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedAlgorithm"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/unsupportedalgorithm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/unsupportedalgorithm"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]]},"sections":[],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/unsupportedAlgorithm":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedAlgorithm","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"MBSCipherErrorUnsupportedAlgorithm","kind":"identifier"}],"role":"symbol","title":"MBSCipherError.Code.unsupportedAlgorithm","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/unsupportedAlgorithm","type":"topic","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/unsupportedalgorithm"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","title":"MbSecureCrypto","role":"collection","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","type":"topic","title":"MBSCipherError.Code","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","abstract":[{"type":"text","text":"Error codes for cipher operations"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MBSCipherErrorUnsupportedAlgorithm"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBSCipherErrorUnsupportedAlgorithm"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MBSCipherErrorUnsupportedAlgorithm","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1unsupportedAlgorithm\/title","value":"MBSCipherErrorUnsupportedAlgorithm"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1unsupportedAlgorithm\/fragments","value":[{"text":"MBSCipherErrorUnsupportedAlgorithm","kind":"identifier"}]},{"value":"MBSCipherError","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBSCipherError"}]},{"value":[{"kind":"identifier","text":"MBSCipherError"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}