{"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/kMBSCipherMaxFileSize","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kMBSCipherMaxFileSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/kmbsciphermaxfilesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mbsecurecrypto\/kmbsciphermaxfilesize"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto"]]},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"MbSecureCrypto"}],"navigatorTitle":[{"text":"kMBSCipherMaxFileSize","kind":"identifier"}],"externalID":"c:@kMBSCipherMaxFileSize","title":"kMBSCipherMaxFileSize","symbolKind":"var","roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kMBSCipherMaxFileSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"role":"collection","type":"topic","kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS.","type":"text"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/kMBSCipherMaxFileSize":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/kMBSCipherMaxFileSize","url":"\/documentation\/mbsecurecrypto\/kmbsciphermaxfilesize","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"kMBSCipherMaxFileSize"}],"title":"kMBSCipherMaxFileSize","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"kMBSCipherMaxFileSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"kMBSCipherMaxFileSize"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"kMBSCipherMaxFileSize"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"kMBSCipherMaxFileSize","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1kMBSCipherMaxFileSize\/title","value":"kMBSCipherMaxFileSize"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1kMBSCipherMaxFileSize\/fragments","value":[{"text":"kMBSCipherMaxFileSize","kind":"identifier"}],"op":"replace"}]}]}