{"metadata":{"role":"symbol","platforms":[{"introducedAt":"15.6","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"deprecated":false,"introducedAt":"15.6","unavailable":false,"name":"iPadOS","beta":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"15.6"}],"externalID":"c:@E@MBSCipherAlgorithm","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"identifier"}],"navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"roleHeading":"Enumeration","title":"MBSCipherAlgorithm","modules":[{"name":"MbSecureCrypto"}],"symbolKind":"enum"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipheralgorithm"]},{"paths":["\/documentation\/mbsecurecrypto\/mbscipheralgorithm"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSCipherAlgorithm"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/AESGCM"],"title":"Enumeration Cases","generated":true},{"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/Equatable-Implementations","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/s15BitwiseCopyableP","doc:\/\/com.mavbozo.mbsecurecrypto\/SQ","doc:\/\/com.mavbozo.mbsecurecrypto\/SH","doc:\/\/com.mavbozo.mbsecurecrypto\/SY","doc:\/\/com.mavbozo.mbsecurecrypto\/s8SendableP"]}],"references":{"doc://com.mavbozo.mbsecurecrypto/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/SH"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/Equatable-Implementations","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm\/equatable-implementations","type":"topic","abstract":[],"kind":"article"},"doc://com.mavbozo.mbsecurecrypto/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/SY"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"kind":"symbol","url":"\/documentation\/mbsecurecrypto","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic","abstract":[{"text":"A secure cryptography library for iOS and macOS.","type":"text"}],"title":"MbSecureCrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/RawRepresentable-Implementations","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm\/rawrepresentable-implementations","type":"topic","abstract":[],"kind":"article"},"doc://com.mavbozo.mbsecurecrypto/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/s8SendableP"},"doc://com.mavbozo.mbsecurecrypto/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/s15BitwiseCopyableP"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm/AESGCM":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/AESGCM","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"AESGCM","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm\/aesgcm","abstract":[],"title":"MBSCipherAlgorithm.AESGCM","type":"topic","navigatorTitle":[{"text":"MBSCipherAlgorithmAESGCM","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/init(rawValue:)"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"type":"topic","abstract":[],"title":"MBSCipherAlgorithm","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBSCipherAlgorithm"}]},"doc://com.mavbozo.mbsecurecrypto/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/SQ"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"introducedAt":"15.6","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"introducedAt":"15.6","unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"15.6","beta":false,"deprecated":false,"unavailable":false}],"op":"replace","path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"MBSCipherAlgorithm","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/AESGCM"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBSCipherAlgorithm","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm~1AESGCM\/title","op":"replace","value":"MBSCipherAlgorithmAESGCM"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm~1AESGCM\/fragments","op":"replace","value":[{"text":"MBSCipherAlgorithmAESGCM","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","op":"replace","value":"MBSCipherAlgorithm"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}