{"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto"]]},"metadata":{"externalID":"c:@M@MbSecureCrypto@objc(cs)MBSCipherBridge","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBSCipherBridge","kind":"identifier"}],"title":"MBSCipherBridge","roleHeading":"Class","symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"MBSCipherBridge","kind":"identifier"}],"modules":[{"name":"MbSecureCrypto"}]},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBSCipherBridge","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/objc(pl)NSObject","doc:\/\/com.mavbozo.mbsecurecrypto\/s7CVarArgP","doc:\/\/com.mavbozo.mbsecurecrypto\/s28CustomDebugStringConvertibleP","doc:\/\/com.mavbozo.mbsecurecrypto\/s23CustomStringConvertibleP","doc:\/\/com.mavbozo.mbsecurecrypto\/SQ","doc:\/\/com.mavbozo.mbsecurecrypto\/SH"],"type":"conformsTo","kind":"relationships"}],"kind":"symbol","topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptData(_:key:algorithm:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptData(_:key:algorithm:format:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptString(_:key:algorithm:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptString(_:key:algorithm:format:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptData(_:key:algorithm:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptData(_:key:algorithm:format:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptString(_:key:algorithm:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptString(_:key:algorithm:format:error:)"],"anchor":"Type-Methods","generated":true}],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/decryptString(_:key:algorithm:format:error:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptString(_:key:algorithm:format:error:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"decryptString","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"text":"algorithm","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","text":"MBSCipherAlgorithm","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"format"},{"text":": ","kind":"text"},{"text":"MBSCipherFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?>?) -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"decryptString(_:key:algorithm:format:error:)","role":"symbol","navigatorTitle":[{"text":"decryptString:key:algorithm:format:error:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptstring(_:key:algorithm:format:error:)"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"url":"\/documentation\/mbsecurecrypto","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS.","type":"text"}],"title":"MbSecureCrypto","role":"collection"},"doc://com.mavbozo.mbsecurecrypto/objc(cs)NSObject":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/decryptData(_:key:algorithm:format:error:)":{"navigatorTitle":[{"text":"decryptData:key:algorithm:format:error:","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"decryptData","kind":"identifier"},{"kind":"text","text":"("},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"algorithm"},{"text":": ","kind":"text"},{"text":"MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"format","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MBSCipherFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherFormat"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":"?>?) -> "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptData(_:key:algorithm:format:error:)","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptdata(_:key:algorithm:format:error:)","abstract":[],"role":"symbol","title":"decryptData(_:key:algorithm:format:error:)"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/init":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/init"},"doc://com.mavbozo.mbsecurecrypto/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/decryptData(_:key:algorithm:error:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptData(_:key:algorithm:error:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decryptData"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"algorithm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","text":"MBSCipherAlgorithm","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?>?) -> "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"decryptData(_:key:algorithm:error:)","role":"symbol","navigatorTitle":[{"text":"decryptData:key:algorithm:error:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptdata(_:key:algorithm:error:)"},"doc://com.mavbozo.mbsecurecrypto/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/encryptString(_:key:algorithm:format:error:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptString(_:key:algorithm:format:error:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"algorithm"},{"text":": ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"kind":"text","text":", "},{"kind":"externalParam","text":"format"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBSCipherFormat","text":"MBSCipherFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?>?) -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"encryptString(_:key:algorithm:format:error:)","role":"symbol","navigatorTitle":[{"text":"encryptString:key:algorithm:format:error:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptstring(_:key:algorithm:format:error:)"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/encryptString(_:key:algorithm:error:)":{"kind":"symbol","title":"encryptString(_:key:algorithm:error:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"text":"algorithm","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":"?>?) -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptString(_:key:algorithm:error:)","abstract":[],"url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptstring(_:key:algorithm:error:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"encryptString:key:algorithm:error:","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/encryptData(_:key:algorithm:error:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"encryptData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"algorithm"},{"kind":"text","text":": "},{"text":"MBSCipherAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":"?>?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptData(_:key:algorithm:error:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"encryptData:key:algorithm:error:"}],"type":"topic","title":"encryptData(_:key:algorithm:error:)","role":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptdata(_:key:algorithm:error:)"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/decryptString(_:key:algorithm:error:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decryptString"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"algorithm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?>?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptstring(_:key:algorithm:error:)","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptString(_:key:algorithm:error:)","role":"symbol","navigatorTitle":[{"text":"decryptString:key:algorithm:error:","kind":"identifier"}],"abstract":[],"title":"decryptString(_:key:algorithm:error:)","kind":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/encryptData(_:key:algorithm:format:error:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptData(_:key:algorithm:format:error:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encryptData","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"algorithm"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","text":"MBSCipherAlgorithm","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"text":"MBSCipherFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherFormat"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?>?) -> "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"encryptData(_:key:algorithm:format:error:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"encryptData:key:algorithm:format:error:"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptdata(_:key:algorithm:format:error:)"},"doc://com.mavbozo.mbsecurecrypto/s7CVarArgP":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mavbozo.mbsecurecrypto/SQ":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mavbozo.mbsecurecrypto/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mavbozo.mbsecurecrypto/SH":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherBridge","kind":"identifier"}],"navigatorTitle":[{"text":"MBSCipherBridge","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherbridge","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge","abstract":[],"title":"MBSCipherBridge","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"MBSCipherBridge"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBSCipherBridge"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherBridge"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/init"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptData(_:key:algorithm:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptData(_:key:algorithm:format:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptString(_:key:algorithm:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptString(_:key:algorithm:format:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptData(_:key:algorithm:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptData(_:key:algorithm:format:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptString(_:key:algorithm:error:)","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptString(_:key:algorithm:format:error:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/objc(cs)NSObject"]}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MBSCipherBridge","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"decryptString:key:algorithm:format:error:","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptString(_:key:algorithm:format:error:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptString(_:key:algorithm:format:error:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"decryptString:key:algorithm:format:error:","kind":"identifier"}]},{"value":"decryptData:key:algorithm:format:error:","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptData(_:key:algorithm:format:error:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptData(_:key:algorithm:format:error:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"decryptData:key:algorithm:format:error:"}],"op":"replace"},{"value":"decryptData:key:algorithm:error:","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptData(_:key:algorithm:error:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptData(_:key:algorithm:error:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"decryptData:key:algorithm:error:","kind":"identifier"}]},{"value":"encryptString:key:algorithm:format:error:","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptString(_:key:algorithm:format:error:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptString(_:key:algorithm:format:error:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"encryptString:key:algorithm:format:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptString(_:key:algorithm:error:)\/title","value":"encryptString:key:algorithm:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptString(_:key:algorithm:error:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"encryptString:key:algorithm:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptData(_:key:algorithm:error:)\/title","value":"encryptData:key:algorithm:error:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"encryptData:key:algorithm:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptData(_:key:algorithm:error:)\/fragments"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptString(_:key:algorithm:error:)\/title","value":"decryptString:key:algorithm:error:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"decryptString:key:algorithm:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptString(_:key:algorithm:error:)\/fragments"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptData(_:key:algorithm:format:error:)\/title","value":"encryptData:key:algorithm:format:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptData(_:key:algorithm:format:error:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"encryptData:key:algorithm:format:error:"}]},{"value":"MBSCipherBridge","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/title"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/fragments","value":[{"text":"MBSCipherBridge","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBSCipherBridge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/navigatorTitle","op":"replace"}]}]}