{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherformat"]},{"paths":["\/documentation\/mbsecurecrypto\/mbscipherformat"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBSCipherFormat"}],"platforms":["iOS"],"languages":["swift"]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/s15BitwiseCopyableP","doc:\/\/com.mavbozo.mbsecurecrypto\/SQ","doc:\/\/com.mavbozo.mbsecurecrypto\/SH","doc:\/\/com.mavbozo.mbsecurecrypto\/SY","doc:\/\/com.mavbozo.mbsecurecrypto\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/V0","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/V1"],"anchor":"Enumeration-Cases","generated":true},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/Equatable-Implementations","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/RawRepresentable-Implementations"]}],"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto"]]},"abstract":[{"type":"text","text":"Supported ciphertext format versions"}],"metadata":{"externalID":"c:@E@MBSCipherFormat","platforms":[{"beta":false,"deprecated":false,"introducedAt":"15.6","name":"iOS","unavailable":false},{"introducedAt":"15.6","deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"15.6","deprecated":false}],"modules":[{"name":"MbSecureCrypto"}],"navigatorTitle":[{"text":"MBSCipherFormat","kind":"identifier"}],"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherFormat","kind":"identifier"}],"symbolKind":"enum","title":"MBSCipherFormat","role":"symbol"},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherFormat/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/RawRepresentable-Implementations","url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/rawrepresentable-implementations","abstract":[],"kind":"article","type":"topic","title":"RawRepresentable Implementations"},"doc://com.mavbozo.mbsecurecrypto/SH":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","type":"topic","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","role":"collection","kind":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherFormat/V1":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/V1","abstract":[{"text":"Reserved for future use","type":"text"}],"title":"MBSCipherFormat.V1","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"V1","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherFormatV1"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/v1"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherFormat/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/Equatable-Implementations","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/equatable-implementations"},"doc://com.mavbozo.mbsecurecrypto/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://com.mavbozo.mbsecurecrypto/SY":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherFormat":{"title":"MBSCipherFormat","abstract":[{"type":"text","text":"Supported ciphertext format versions"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","type":"topic","navigatorTitle":[{"text":"MBSCipherFormat","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherFormat","kind":"identifier"}],"role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherFormat/V0":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/V0","navigatorTitle":[{"text":"MBSCipherFormatV0","kind":"identifier"}],"title":"MBSCipherFormat.V0","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"V0","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/v0","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Format V0: [12B nonce][ciphertext][16B tag]"}]},"doc://com.mavbozo.mbsecurecrypto/SQ":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mavbozo.mbsecurecrypto/s8SendableP":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherFormat/init(rawValue:)":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/init(rawvalue:)","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"name":"iOS","introducedAt":"15.6","deprecated":false,"beta":false},{"beta":false,"deprecated":false,"introducedAt":"15.6","name":"iPadOS","unavailable":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"15.6"}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"MBSCipherFormat","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBSCipherFormat","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherFormat"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/V0","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/V1"],"anchor":"Enumeration-Cases","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBSCipherFormat","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat~1V1\/title","value":"MBSCipherFormatV1"},{"value":[{"kind":"identifier","text":"MBSCipherFormatV1"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat~1V1\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/title","value":"MBSCipherFormat"},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherFormat"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/fragments"},{"op":"replace","value":[{"text":"MBSCipherFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat~1V0\/title","value":"MBSCipherFormatV0"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat~1V0\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBSCipherFormatV0"}]}]}]}