{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSErrorDomain","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto"]]},"metadata":{"modules":[{"name":"MbSecureCrypto"}],"roleHeading":"Global Variable","title":"MBSErrorDomain","externalID":"c:@MBSErrorDomain","symbolKind":"var","role":"symbol","navigatorTitle":[{"text":"MBSErrorDomain","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBSErrorDomain"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbserrordomain"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mbsecurecrypto\/mbserrordomain"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSErrorDomain":{"title":"MBSErrorDomain","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"MBSErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"MBSErrorDomain"}],"abstract":[],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSErrorDomain","url":"\/documentation\/mbsecurecrypto\/mbserrordomain","kind":"symbol","type":"topic","role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","kind":"symbol","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"role":"collection","url":"\/documentation\/mbsecurecrypto","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"value":"MBSErrorDomain","path":"\/metadata\/title","op":"replace"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MBSErrorDomain","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"MBSErrorDomain","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSErrorDomain\/title","value":"MBSErrorDomain"},{"op":"replace","value":[{"kind":"identifier","text":"MBSErrorDomain"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSErrorDomain\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}