{"abstract":[{"type":"text","text":"Decrypts an encrypted string using authenticated encryption."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"decryptString:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"encryptedString","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withAlgorithm:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","text":"MBSCipherAlgorithm","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"algorithm"},{"kind":"text","text":" "},{"kind":"identifier","text":"withFormat:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"text":"format","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withKey:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Base64-encoded string containing [nonce][ciphertext][tag]","type":"text"}]}],"name":"encryptedString"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Must match the algorithm used for encryption","type":"text"}]}],"name":"algorithm"},{"name":"format","content":[{"inlineContent":[{"type":"text","text":"Encryption format version to use"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Must be the same 32-byte key used for encryption","type":"text"}]}],"name":"key"},{"content":[{"inlineContent":[{"text":"Error object populated on failure with codes:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"MBSCipherErrorInvalidKey (200): Invalid key size"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorInvalidInput (202): Invalid\/corrupted input"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorUnsupportedFormat (204): Unknown or unsupported format version","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"MBSCipherErrorFormatDetectionFailed (205): Failed to detect format version"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorFormatMismatch (206): Format version mismatch during decryption","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorDecryptionFailed (211): Decryption operation failed"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"MBSCipherErrorAuthenticationFailed (212): Tag verification failed"}],"type":"paragraph"}]}],"type":"unorderedList"}],"name":"error"}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The original decrypted string, or nil on failure"}],"type":"paragraph"}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Decrypts a string previously encrypted by encryptString:withAlgorithm:withKey:."},{"type":"text","text":" "},{"text":"Verifies the authentication tag before returning the decrypted data.","type":"text"}]},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Decryption will fail if the data has been modified or if an incorrect key is used"}]}]}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher"]]},"metadata":{"externalID":"c:objc(cs)MBSCipher(cm)decryptString:withAlgorithm:withFormat:withKey:error:","title":"decryptString:withAlgorithm:withFormat:withKey:error:","navigatorTitle":[{"text":"decryptString:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"MbSecureCrypto"}],"role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"decryptString:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher\/decryptString:withAlgorithm:withFormat:withKey:error:"},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipher\/decryptstring:withalgorithm:withformat:withkey:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"url":"\/documentation\/mbsecurecrypto","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS.","type":"text"}],"title":"MbSecureCrypto","role":"collection"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"kind":"symbol","title":"MBSCipherAlgorithm","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","abstract":[],"url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","role":"symbol","type":"topic","navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipher":{"abstract":[{"text":"A secure encryption and decryption utility that implements authenticated encryption.","type":"text"}],"url":"\/documentation\/mbsecurecrypto\/mbscipher","fragments":[{"text":"MBSCipher","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"MBSCipher","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipher/decryptString:withAlgorithm:withFormat:withKey:error:":{"fragments":[{"kind":"text","text":"+ "},{"text":"decryptString:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Decrypts an encrypted string using authenticated encryption."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"decryptString:withAlgorithm:withFormat:withKey:error:"}],"title":"decryptString:withAlgorithm:withFormat:withKey:error:","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbscipher\/decryptstring:withalgorithm:withformat:withkey:error:","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher\/decryptString:withAlgorithm:withFormat:withKey:error:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","op":"replace","value":"MBSCipherAlgorithm"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}