{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"decryptFile:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"sourceURL","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toOutput:"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"destinationURL"},{"text":" ","kind":"text"},{"text":"withAlgorithm:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm"},{"text":") ","kind":"text"},{"text":"algorithm","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *) "},{"text":"format","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withKey:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},{"parameters":[{"name":"sourceURL","content":[{"inlineContent":[{"type":"text","text":"Encrypted file containing [nonce][ciphertext][tag]"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Where to write the decrypted file"}],"type":"paragraph"}],"name":"destinationURL"},{"name":"algorithm","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Must match the algorithm used for encryption"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Encryption format version to use"}]}],"name":"format"},{"name":"key","content":[{"inlineContent":[{"text":"Must be the same 32-byte key used for encryption","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"Error object populated on failure with codes:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"MBSCipherErrorInvalidKey (200): Invalid key size","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"MBSCipherErrorInvalidInput (202): Invalid\/corrupted input"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"MBSCipherErrorUnsupportedFormat (204): Unknown or unsupported format version","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorFormatDetectionFailed (205): Failed to detect format version"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorFormatMismatch (206): Format version mismatch during decryption","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorIOFailure (220): File read\/write failed","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorFilePermission (222): Insufficient permissions"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorDecryptionFailed (211): Decryption operation failed"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorAuthenticationFailed (212): Tag verification failed"}]}]}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"YES if successful, NO if an error occurred"}],"type":"paragraph"}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Decrypts a file previously encrypted by encryptFile:toOutput:withAlgorithm:withKey:.","type":"text"},{"type":"text","text":" "},{"text":"Verifies the authentication tag before writing the decrypted data.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipher\/decryptfile:tooutput:withalgorithm:withformat:withkey:error:"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"decryptFile:toOutput:withAlgorithm:withFormat:withKey:error:"}],"roleHeading":"Type Method","symbolKind":"method","title":"decryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","modules":[{"name":"MbSecureCrypto"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"decryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"externalID":"c:objc(cs)MBSCipher(cm)decryptFile:toOutput:withAlgorithm:withFormat:withKey:error:"},"abstract":[{"text":"Decrypts an encrypted file using authenticated encryption.","type":"text"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher\/decryptFile:toOutput:withAlgorithm:withFormat:withKey:error:"},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"abstract":[],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","role":"symbol","title":"MBSCipherAlgorithm","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBSCipherAlgorithm","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipher/decryptFile:toOutput:withAlgorithm:withFormat:withKey:error:":{"title":"decryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher\/decryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","abstract":[{"type":"text","text":"Decrypts an encrypted file using authenticated encryption."}],"navigatorTitle":[{"text":"decryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbscipher\/decryptfile:tooutput:withalgorithm:withformat:withkey:error:","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"decryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","title":"MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"role":"collection","type":"topic","url":"\/documentation\/mbsecurecrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipher":{"abstract":[{"type":"text","text":"A secure encryption and decryption utility that implements authenticated encryption."}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher","url":"\/documentation\/mbsecurecrypto\/mbscipher","fragments":[{"kind":"identifier","text":"MBSCipher"}],"title":"MBSCipher"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","value":"MBSCipherAlgorithm"},{"value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle"}]}]}