{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Decrypts encrypted data using authenticated encryption."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"decryptData:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"text":"encryptedData","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withAlgorithm:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","kind":"typeIdentifier","text":"MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"text":") ","kind":"text"},{"text":"algorithm","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withKey:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"key","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Data containing [nonce][ciphertext][tag]"}]}],"name":"encryptedData"},{"name":"algorithm","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Must match the algorithm used for encryption"}]}]},{"name":"key","content":[{"inlineContent":[{"text":"Must be the same 32-byte key used for encryption","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Error object populated on failure with codes:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"MBSCipherErrorInvalidKey (200): Invalid key size"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorInvalidInput (202): Invalid\/corrupted input"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorDecryptionFailed (211): Decryption operation failed","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorAuthenticationFailed (212): Tag verification failed"}]}]}]}],"name":"error"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The original decrypted data, or nil on failure","type":"text"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Decrypts data previously encrypted by encryptData:withAlgorithm:withKey:.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Verifies the authentication tag before returning the decrypted data."}]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher\/decryptData:withAlgorithm:withKey:error:"},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipher\/decryptdata:withalgorithm:withkey:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"decryptData:withAlgorithm:withKey:error:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"decryptData:withAlgorithm:withKey:error:","kind":"identifier"}],"modules":[{"name":"MbSecureCrypto"}],"roleHeading":"Type Method","externalID":"c:objc(cs)MBSCipher(cm)decryptData:withAlgorithm:withKey:error:","role":"symbol","symbolKind":"method","title":"decryptData:withAlgorithm:withKey:error:"},"sections":[],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"kind":"symbol","url":"\/documentation\/mbsecurecrypto","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic","abstract":[{"text":"A secure cryptography library for iOS and macOS.","type":"text"}],"title":"MbSecureCrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipher/decryptData:withAlgorithm:withKey:error:":{"navigatorTitle":[{"text":"decryptData:withAlgorithm:withKey:error:","kind":"identifier"}],"title":"decryptData:withAlgorithm:withKey:error:","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher\/decryptData:withAlgorithm:withKey:error:","abstract":[{"type":"text","text":"Decrypts encrypted data using authenticated encryption."}],"fragments":[{"text":"+ ","kind":"text"},{"text":"decryptData:withAlgorithm:withKey:error:","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbscipher\/decryptdata:withalgorithm:withkey:error:"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipher":{"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher","kind":"symbol","title":"MBSCipher","role":"symbol","fragments":[{"kind":"identifier","text":"MBSCipher"}],"url":"\/documentation\/mbsecurecrypto\/mbscipher","abstract":[{"type":"text","text":"A secure encryption and decryption utility that implements authenticated encryption."}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"type":"topic","abstract":[],"title":"MBSCipherAlgorithm","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBSCipherAlgorithm"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","value":"MBSCipherAlgorithm","op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","op":"replace","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}