{"abstract":[{"text":"Encrypts arbitrary data using authenticated encryption.","type":"text"}],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipher\/encryptdata:withalgorithm:withformat:withkey:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipher"]]},"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipher\/encryptData:withAlgorithm:withFormat:withKey:error:","interfaceLanguage":"occ"},"sections":[],"metadata":{"fragments":[{"text":"+ ","kind":"text"},{"text":"encryptData:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)MBSCipher(cm)encryptData:withAlgorithm:withFormat:withKey:error:","navigatorTitle":[{"text":"encryptData:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"modules":[{"name":"MbSecureCrypto"}],"title":"encryptData:withAlgorithm:withFormat:withKey:error:"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"encryptData:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"data","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withAlgorithm:","kind":"identifier"},{"kind":"text","text":"("},{"text":"MBSCipherAlgorithm","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"text":") ","kind":"text"},{"text":"algorithm","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withFormat:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"format"},{"kind":"text","text":" "},{"text":"withKey:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The data to encrypt"}]}]},{"name":"algorithm","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Currently only supports MBSCipherAlgorithmAESGCM"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Encryption format version to use:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"MBSCipherFormatV0: Legacy format [nonce][ciphertext][tag]","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherFormatV1: Universal format with algorithm parameters","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"nil: Defaults to V0 for backward compatibility","type":"text"}],"type":"paragraph"}]}]}],"name":"format"},{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"32-byte key for AES-256-GCM"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Error object populated on failure with codes:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorInvalidKey (200): Invalid key size","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorInvalidInput (202): Invalid input data"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorUnsupportedFormat (204): Unknown or unsupported format version","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"MBSCipherErrorFormatDetectionFailed (205): Failed to detect format version","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorFormatMismatch (206): Format version mismatch during decryption"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"MBSCipherErrorEncryptionFailed (210): Encryption operation failed"}],"type":"paragraph"}]}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"NSData or nil on failure"}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Encrypts the provided data using AES-GCM with a random nonce. The output"},{"text":" ","type":"text"},{"text":"includes everything needed for decryption: nonce, ciphertext, and tag.","type":"text"}],"type":"paragraph"},{"style":"note","name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"MBSCipherFormatV1 format provides enhanced algorithm flexibility and"},{"type":"text","text":" "},{"type":"text","text":"standardized parameter handling"}],"type":"paragraph"}]}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipher/encryptData:withAlgorithm:withFormat:withKey:error:":{"kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipher\/encryptData:withAlgorithm:withFormat:withKey:error:","type":"topic","navigatorTitle":[{"text":"encryptData:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"encryptData:withAlgorithm:withFormat:withKey:error:"}],"title":"encryptData:withAlgorithm:withFormat:withKey:error:","role":"symbol","abstract":[{"type":"text","text":"Encrypts arbitrary data using authenticated encryption."}],"url":"\/documentation\/mbsecurecrypto\/mbscipher\/encryptdata:withalgorithm:withformat:withkey:error:"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipher":{"fragments":[{"kind":"identifier","text":"MBSCipher"}],"title":"MBSCipher","kind":"symbol","type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipher","url":"\/documentation\/mbsecurecrypto\/mbscipher","abstract":[{"type":"text","text":"A secure encryption and decryption utility that implements authenticated encryption."}],"role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","role":"collection","type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"type":"topic","navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"kind":"symbol","title":"MBSCipherAlgorithm","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSCipherAlgorithm"}],"url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","abstract":[{"text":"Supported Cipher Algorithms","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","value":"MBSCipherAlgorithm","op":"replace"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}]}]}]}