{"sections":[],"metadata":{"fragments":[{"text":"+ ","kind":"text"},{"text":"encryptString:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"externalID":"c:objc(cs)MBSCipher(cm)encryptString:withAlgorithm:withFormat:withKey:error:","title":"encryptString:withAlgorithm:withFormat:withKey:error:","modules":[{"name":"MbSecureCrypto"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"encryptString:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher\/encryptString:withAlgorithm:withFormat:withKey:error:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Encrypts a string using authenticated encryption with specified format."}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipher\/encryptstring:withalgorithm:withformat:withkey:error:"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"encryptString:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"string"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withAlgorithm:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","text":"MBSCipherAlgorithm","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"algorithm"},{"text":" ","kind":"text"},{"text":"withFormat:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"format","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withKey:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The string to encrypt (must be valid UTF-8)"}]}],"name":"string"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Currently only supports MBSCipherAlgorithmAESGCM"}]}],"name":"algorithm"},{"content":[{"inlineContent":[{"text":"Encryption format version to use","type":"text"}],"type":"paragraph"}],"name":"format"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"32-byte key for AES-256-GCM"}]}],"name":"key"},{"content":[{"inlineContent":[{"type":"text","text":"Error object populated on failure with codes:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorInvalidKey (200): Invalid key size"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorInvalidInput (202): Invalid input data","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"MBSCipherErrorUnsupportedFormat (204): Unknown or unsupported format version","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"MBSCipherErrorFormatDetectionFailed (205): Failed to detect format version"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorFormatMismatch (206): Format version mismatch during decryption"}]}]},{"content":[{"inlineContent":[{"text":"MBSCipherErrorEncryptionFailed (210): Encryption operation failed","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorUnsupportedFormat (204): Format version not supported","type":"text"}]}]}]}],"name":"error"}]},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Base64-encoded string containing format-specific encrypted data, or nil on failure"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Encrypts the UTF-8 representation of the string using AES-GCM with a random nonce.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The output includes format-specific components needed for decryption."}]}]}],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher"]]},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipher":{"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher","kind":"symbol","title":"MBSCipher","role":"symbol","fragments":[{"kind":"identifier","text":"MBSCipher"}],"url":"\/documentation\/mbsecurecrypto\/mbscipher","abstract":[{"type":"text","text":"A secure encryption and decryption utility that implements authenticated encryption."}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"type":"topic","abstract":[],"title":"MBSCipherAlgorithm","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBSCipherAlgorithm"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"kind":"symbol","url":"\/documentation\/mbsecurecrypto","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic","abstract":[{"text":"A secure cryptography library for iOS and macOS.","type":"text"}],"title":"MbSecureCrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipher/encryptString:withAlgorithm:withFormat:withKey:error:":{"type":"topic","abstract":[{"type":"text","text":"Encrypts a string using authenticated encryption with specified format."}],"fragments":[{"text":"+ ","kind":"text"},{"text":"encryptString:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher\/encryptString:withAlgorithm:withFormat:withKey:error:","navigatorTitle":[{"text":"encryptString:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"title":"encryptString:withAlgorithm:withFormat:withKey:error:","kind":"symbol","role":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipher\/encryptstring:withalgorithm:withformat:withkey:error:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","value":"MBSCipherAlgorithm","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","op":"replace","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}]}]}]}