{"abstract":[{"type":"text","text":"Encrypts a file using authenticated encryption."}],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"encryptFile:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sourceURL"},{"text":" ","kind":"text"},{"text":"toOutput:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"destinationURL"},{"text":" ","kind":"text"},{"text":"withAlgorithm:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","text":"MBSCipherAlgorithm"},{"kind":"text","text":") "},{"text":"algorithm","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withFormat:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"format","kind":"internalParam"},{"kind":"text","text":" "},{"text":"withKey:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"sourceURL","content":[{"type":"paragraph","inlineContent":[{"text":"File to encrypt (must be readable and ≤ 10MB)","type":"text"}]}]},{"name":"destinationURL","content":[{"inlineContent":[{"text":"Where to write the encrypted file","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Currently only supports MBSCipherAlgorithmAESGCM"}],"type":"paragraph"}],"name":"algorithm"},{"name":"format","content":[{"inlineContent":[{"text":"Encryption format version to use","type":"text"}],"type":"paragraph"}]},{"name":"key","content":[{"inlineContent":[{"text":"32-byte key for AES-256-GCM","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Error object populated on failure with codes:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorInvalidKey (200): Invalid key size","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorUnsupportedFormat (204): Unknown or unsupported format version","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"MBSCipherErrorFormatDetectionFailed (205): Failed to detect format version","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorFormatMismatch (206): Format version mismatch during decryption"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorFileTooLarge (221): File exceeds 10MB limit"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"MBSCipherErrorIOFailure (220): File read\/write failed"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorFilePermission (222): Insufficient permissions"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorEncryptionFailed (210): Encryption operation failed","type":"text"}]}]}]}],"name":"error"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES if successful, NO if an error occurred"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"Encrypts the contents of a file using AES-GCM with a random nonce. The encrypted","type":"text"},{"type":"text","text":" "},{"type":"text","text":"file will include the nonce and authentication tag needed for decryption."}],"type":"paragraph"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The encrypted file will be 28 bytes larger than the source file"}]}],"name":"Note"}]}],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipher\/encryptfile:tooutput:withalgorithm:withformat:withkey:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher\/encryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"MbSecureCrypto"}],"role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"encryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"externalID":"c:objc(cs)MBSCipher(cm)encryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","symbolKind":"method","navigatorTitle":[{"text":"encryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"title":"encryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","roleHeading":"Type Method"},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"abstract":[],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","role":"symbol","title":"MBSCipherAlgorithm","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBSCipherAlgorithm","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipher":{"abstract":[{"type":"text","text":"A secure encryption and decryption utility that implements authenticated encryption."}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher","url":"\/documentation\/mbsecurecrypto\/mbscipher","fragments":[{"kind":"identifier","text":"MBSCipher"}],"title":"MBSCipher"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipher/encryptFile:toOutput:withAlgorithm:withFormat:withKey:error:":{"kind":"symbol","abstract":[{"text":"Encrypts a file using authenticated encryption.","type":"text"}],"role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"encryptFile:toOutput:withAlgorithm:withFormat:withKey:error:"}],"url":"\/documentation\/mbsecurecrypto\/mbscipher\/encryptfile:tooutput:withalgorithm:withformat:withkey:error:","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher\/encryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","navigatorTitle":[{"text":"encryptFile:toOutput:withAlgorithm:withFormat:withKey:error:","kind":"identifier"}],"type":"topic","title":"encryptFile:toOutput:withAlgorithm:withFormat:withKey:error:"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","title":"MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"role":"collection","type":"topic","url":"\/documentation\/mbsecurecrypto"}},"variantOverrides":[{"patch":[{"value":"MBSCipherAlgorithm","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}