{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipher\/encryptfile:tooutput:withalgorithm:withkey:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipher"]]},"metadata":{"externalID":"c:objc(cs)MBSCipher(cm)encryptFile:toOutput:withAlgorithm:withKey:error:","navigatorTitle":[{"text":"encryptFile:toOutput:withAlgorithm:withKey:error:","kind":"identifier"}],"modules":[{"name":"MbSecureCrypto"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"encryptFile:toOutput:withAlgorithm:withKey:error:"}],"title":"encryptFile:toOutput:withAlgorithm:withKey:error:"},"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipher\/encryptFile:toOutput:withAlgorithm:withKey:error:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"encryptFile:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" *) "},{"text":"sourceURL","kind":"internalParam"},{"kind":"text","text":" "},{"text":"toOutput:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"destinationURL","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withAlgorithm:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","text":"MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"algorithm","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"withKey:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"]}]},{"kind":"parameters","parameters":[{"name":"sourceURL","content":[{"type":"paragraph","inlineContent":[{"text":"File to encrypt (must be readable and ≤ 10MB)","type":"text"}]}]},{"name":"destinationURL","content":[{"type":"paragraph","inlineContent":[{"text":"Where to write the encrypted file","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Currently only supports MBSCipherAlgorithmAESGCM","type":"text"}]}],"name":"algorithm"},{"content":[{"inlineContent":[{"text":"32-byte key for AES-256-GCM","type":"text"}],"type":"paragraph"}],"name":"key"},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"Error object populated on failure with codes:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"MBSCipherErrorInvalidKey (200): Invalid key size"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorFileTooLarge (221): File exceeds 10MB limit"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"MBSCipherErrorIOFailure (220): File read\/write failed"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorFilePermission (222): Insufficient permissions","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"MBSCipherErrorEncryptionFailed (210): Encryption operation failed","type":"text"}]}]}]}]}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES if successful, NO if an error occurred"}]}]},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Encrypts the contents of a file using AES-GCM with a random nonce. The encrypted","type":"text"},{"type":"text","text":" "},{"type":"text","text":"file will include the nonce and authentication tag needed for decryption."}]},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"default to using format MBSCipherFormatV0","type":"text"}]}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Encrypts a file using authenticated encryption."}],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"type":"topic","navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"kind":"symbol","title":"MBSCipherAlgorithm","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSCipherAlgorithm"}],"url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","abstract":[{"text":"Supported Cipher Algorithms","type":"text"}],"role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","role":"collection","type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipher":{"fragments":[{"kind":"identifier","text":"MBSCipher"}],"title":"MBSCipher","kind":"symbol","type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipher","url":"\/documentation\/mbsecurecrypto\/mbscipher","abstract":[{"type":"text","text":"A secure encryption and decryption utility that implements authenticated encryption."}],"role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipher/encryptFile:toOutput:withAlgorithm:withKey:error:":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipher\/encryptFile:toOutput:withAlgorithm:withKey:error:","kind":"symbol","abstract":[{"type":"text","text":"Encrypts a file using authenticated encryption."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"encryptFile:toOutput:withAlgorithm:withKey:error:"}],"type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"encryptFile:toOutput:withAlgorithm:withKey:error:","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipher\/encryptfile:tooutput:withalgorithm:withkey:error:","title":"encryptFile:toOutput:withAlgorithm:withKey:error:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","op":"replace","value":"MBSCipherAlgorithm"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"op":"replace"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}