{"metadata":{"title":"!=(_:_:)","extendedModule":"Swift","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@E@MBSCipherError","role":"symbol","symbolKind":"op","roleHeading":"Operator","modules":[{"name":"MbSecureCrypto","relatedModules":["Swift"]}]},"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/Equatable-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"text":".","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/!=(_:_:)"},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","title":"MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"role":"collection","type":"topic","url":"\/documentation\/mbsecurecrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/!=(_:_:)":{"abstract":[],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/!=(_:_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/!=(_:_:)","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"type":"topic","abstract":[{"type":"text","text":"Error codes for cipher operations"}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","title":"MBSCipherError.Code"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/Equatable-Implementations":{"type":"topic","abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/equatable-implementations","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/Equatable-Implementations","title":"Equatable Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","value":"MBSCipherError"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MBSCipherError"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherError"}]}]}]}