{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptionFailed","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@E@MBSCipherError@MBSCipherErrorDecryptionFailed","roleHeading":"Case","symbolKind":"case","title":"MBSCipherError.Code.decryptionFailed","modules":[{"name":"MbSecureCrypto"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decryptionFailed"}],"platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.6"},{"introducedAt":"15.6","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"15.6","beta":false,"deprecated":false}],"navigatorTitle":[{"text":"MBSCipherErrorDecryptionFailed","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/decryptionFailed","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]]},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/decryptionfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/decryptionfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/decryptionFailed":{"role":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/decryptionfailed","navigatorTitle":[{"text":"MBSCipherErrorDecryptionFailed","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/decryptionFailed","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptionFailed","kind":"identifier"}],"type":"topic","kind":"symbol","title":"MBSCipherError.Code.decryptionFailed"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","type":"topic","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","role":"collection","kind":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","title":"MBSCipherError.Code","abstract":[{"text":"Error codes for cipher operations","type":"text"}],"navigatorTitle":[{"text":"Code","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MBSCipherErrorDecryptionFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBSCipherErrorDecryptionFailed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MBSCipherErrorDecryptionFailed","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"MBSCipherErrorDecryptionFailed","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1decryptionFailed\/title"},{"value":[{"kind":"identifier","text":"MBSCipherErrorDecryptionFailed"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1decryptionFailed\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","value":"MBSCipherError"},{"value":[{"kind":"identifier","text":"MBSCipherError"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments"},{"value":[{"text":"MBSCipherError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle"}]}]}