{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"encryptionFailed","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/encryptionFailed"},"kind":"symbol","metadata":{"platforms":[{"introducedAt":"15.6","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"15.6","name":"iPadOS","deprecated":false,"beta":false},{"introducedAt":"15.6","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptionFailed","kind":"identifier"}],"modules":[{"name":"MbSecureCrypto"}],"externalID":"c:@E@MBSCipherError@MBSCipherErrorEncryptionFailed","title":"MBSCipherError.Code.encryptionFailed","navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorEncryptionFailed"}],"roleHeading":"Case","symbolKind":"case"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/encryptionfailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/encryptionfailed"]}],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/encryptionFailed":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/encryptionFailed","title":"MBSCipherError.Code.encryptionFailed","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/encryptionfailed","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encryptionFailed"}],"type":"topic","navigatorTitle":[{"text":"MBSCipherErrorEncryptionFailed","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"type":"topic","url":"\/documentation\/mbsecurecrypto","role":"collection","kind":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","title":"MBSCipherError.Code","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}],"role":"symbol","abstract":[{"type":"text","text":"Error codes for cipher operations"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"MBSCipherErrorEncryptionFailed","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MBSCipherErrorEncryptionFailed","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"MBSCipherErrorEncryptionFailed","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1encryptionFailed\/title","value":"MBSCipherErrorEncryptionFailed","op":"replace"},{"value":[{"kind":"identifier","text":"MBSCipherErrorEncryptionFailed"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1encryptionFailed\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","value":"MBSCipherError"},{"value":[{"kind":"identifier","text":"MBSCipherError"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","op":"replace","value":[{"text":"MBSCipherError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}