{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"filePermission","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/filePermission"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/filepermission"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/filepermission"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]]},"metadata":{"roleHeading":"Case","externalID":"c:@E@MBSCipherError@MBSCipherErrorFilePermission","platforms":[{"introducedAt":"15.6","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"15.6"},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"15.6","beta":false,"deprecated":false}],"navigatorTitle":[{"text":"MBSCipherErrorFilePermission","kind":"identifier"}],"role":"symbol","modules":[{"name":"MbSecureCrypto"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"filePermission"}],"title":"MBSCipherError.Code.filePermission"},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","role":"collection","type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"title":"MBSCipherError.Code","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","abstract":[{"type":"text","text":"Error codes for cipher operations"}],"navigatorTitle":[{"text":"Code","kind":"identifier"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/filePermission":{"role":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/filepermission","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/filePermission","kind":"symbol","type":"topic","title":"MBSCipherError.Code.filePermission","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"filePermission","kind":"identifier"}],"navigatorTitle":[{"text":"MBSCipherErrorFilePermission","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MBSCipherErrorFilePermission"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherErrorFilePermission"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MBSCipherErrorFilePermission","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"MBSCipherError","op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","op":"replace","value":[{"text":"MBSCipherError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","value":[{"text":"MBSCipherError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1filePermission\/title","value":"MBSCipherErrorFilePermission","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1filePermission\/fragments","value":[{"kind":"identifier","text":"MBSCipherErrorFilePermission"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}