{"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formatDetectionFailed"}],"role":"symbol","platforms":[{"deprecated":false,"introducedAt":"15.6","unavailable":false,"name":"iOS","beta":false},{"introducedAt":"15.6","deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"introducedAt":"15.6","beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false}],"externalID":"c:@E@MBSCipherError@MBSCipherErrorFormatDetectionFailed","modules":[{"name":"MbSecureCrypto"}],"symbolKind":"case","title":"MBSCipherError.Code.formatDetectionFailed","navigatorTitle":[{"text":"MBSCipherErrorFormatDetectionFailed","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/formatdetectionfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/formatdetectionfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/formatDetectionFailed","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"formatDetectionFailed","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]]},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","title":"MBSCipherError.Code","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}],"role":"symbol","abstract":[{"type":"text","text":"Error codes for cipher operations"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/formatDetectionFailed":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorFormatDetectionFailed"}],"title":"MBSCipherError.Code.formatDetectionFailed","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/formatdetectionfailed","abstract":[],"type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/formatDetectionFailed","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"formatDetectionFailed","kind":"identifier"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"type":"topic","url":"\/documentation\/mbsecurecrypto","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"MBSCipherErrorFormatDetectionFailed","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"MBSCipherErrorFormatDetectionFailed"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MBSCipherErrorFormatDetectionFailed"}]}],"kind":"declarations"},"op":"replace"},{"value":"MBSCipherError","op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title"},{"value":[{"text":"MBSCipherError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","value":[{"text":"MBSCipherError","kind":"identifier"}],"op":"replace"},{"value":"MBSCipherErrorFormatDetectionFailed","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1formatDetectionFailed\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1formatDetectionFailed\/fragments","value":[{"text":"MBSCipherErrorFormatDetectionFailed","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}