{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"formatMismatch","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/formatmismatch"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/formatmismatch"]}],"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/formatMismatch","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"MbSecureCrypto"}],"roleHeading":"Case","title":"MBSCipherError.Code.formatMismatch","symbolKind":"case","platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false,"introducedAt":"15.6"},{"deprecated":false,"beta":false,"introducedAt":"15.6","name":"iPadOS","unavailable":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"15.6","beta":false}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formatMismatch","kind":"identifier"}],"externalID":"c:@E@MBSCipherError@MBSCipherErrorFormatMismatch","navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorFormatMismatch"}]},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/formatMismatch":{"abstract":[],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/formatMismatch","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formatMismatch"}],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/formatmismatch","title":"MBSCipherError.Code.formatMismatch","navigatorTitle":[{"text":"MBSCipherErrorFormatMismatch","kind":"identifier"}],"role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","type":"topic","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","role":"collection","kind":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","title":"MBSCipherError.Code","abstract":[{"text":"Error codes for cipher operations","type":"text"}],"navigatorTitle":[{"text":"Code","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"MBSCipherErrorFormatMismatch","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MBSCipherErrorFormatMismatch","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBSCipherErrorFormatMismatch"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1formatMismatch\/title","value":"MBSCipherErrorFormatMismatch"},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherErrorFormatMismatch"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1formatMismatch\/fragments"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","value":"MBSCipherError","op":"replace"},{"value":[{"kind":"identifier","text":"MBSCipherError"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherError"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}