{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/invalidinput"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/invalidinput"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"case","modules":[{"name":"MbSecureCrypto"}],"navigatorTitle":[{"text":"MBSCipherErrorInvalidInput","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidInput","kind":"identifier"}],"externalID":"c:@E@MBSCipherError@MBSCipherErrorInvalidInput","roleHeading":"Case","role":"symbol","title":"MBSCipherError.Code.invalidInput","platforms":[{"beta":false,"introducedAt":"15.6","unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"15.6","name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"15.6","name":"Mac Catalyst","unavailable":false}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidInput"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidInput","interfaceLanguage":"swift"},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"title":"MBSCipherError.Code","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Code"}],"abstract":[{"type":"text","text":"Error codes for cipher operations"}],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","type":"topic","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}],"title":"MbSecureCrypto","kind":"symbol","url":"\/documentation\/mbsecurecrypto","role":"collection"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/invalidInput":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidInput"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidInput","navigatorTitle":[{"text":"MBSCipherErrorInvalidInput","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/invalidinput","title":"MBSCipherError.Code.invalidInput"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MBSCipherErrorInvalidInput","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"MBSCipherErrorInvalidInput","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MBSCipherErrorInvalidInput"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"MBSCipherError","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MBSCipherError"}]},{"value":[{"text":"MBSCipherError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1invalidInput\/title","op":"replace","value":"MBSCipherErrorInvalidInput"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1invalidInput\/fragments","op":"replace","value":[{"text":"MBSCipherErrorInvalidInput","kind":"identifier"}]}]}]}