{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"MbSecureCrypto"}],"roleHeading":"Case","title":"MBSCipherError.Code.invalidIV","role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorInvalidIV"}],"platforms":[{"beta":false,"name":"iOS","deprecated":false,"introducedAt":"15.6","unavailable":false},{"beta":false,"introducedAt":"15.6","name":"iPadOS","deprecated":false,"unavailable":false},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"15.6"}],"externalID":"c:@E@MBSCipherError@MBSCipherErrorInvalidIV","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidIV","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]]},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/invalidiv"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/invalidiv"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidIV"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidIV"},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/invalidIV":{"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/invalidiv","kind":"symbol","title":"MBSCipherError.Code.invalidIV","navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorInvalidIV"}],"abstract":[],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidIV","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidIV","kind":"identifier"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"url":"\/documentation\/mbsecurecrypto","title":"MbSecureCrypto","kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","title":"MBSCipherError.Code","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","role":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","abstract":[{"text":"Error codes for cipher operations","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBSCipherErrorInvalidIV","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBSCipherErrorInvalidIV"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBSCipherErrorInvalidIV"}],"platforms":["iOS"]}]}},{"value":"MBSCipherErrorInvalidIV","op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1invalidIV\/title"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1invalidIV\/fragments","value":[{"text":"MBSCipherErrorInvalidIV","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","value":"MBSCipherError","op":"replace"},{"value":[{"kind":"identifier","text":"MBSCipherError"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBSCipherError","kind":"identifier"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle"}]}]}