{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedFormat","kind":"identifier"}],"title":"MBSCipherError.Code.unsupportedFormat","externalID":"c:@E@MBSCipherError@MBSCipherErrorUnsupportedFormat","roleHeading":"Case","role":"symbol","modules":[{"name":"MbSecureCrypto"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"15.6","deprecated":false},{"name":"iPadOS","introducedAt":"15.6","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"15.6"}],"navigatorTitle":[{"text":"MBSCipherErrorUnsupportedFormat","kind":"identifier"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedFormat"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/unsupportedformat"]},{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/unsupportedformat"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/unsupportedFormat","interfaceLanguage":"swift"},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","title":"MBSCipherError.Code","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","role":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","abstract":[{"text":"Error codes for cipher operations","type":"text"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/unsupportedFormat":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unsupportedFormat","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/unsupportedformat","title":"MBSCipherError.Code.unsupportedFormat","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/unsupportedFormat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorUnsupportedFormat"}],"type":"topic","abstract":[]},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"url":"\/documentation\/mbsecurecrypto","title":"MbSecureCrypto","kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MBSCipherErrorUnsupportedFormat","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"MBSCipherErrorUnsupportedFormat","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"MBSCipherErrorUnsupportedFormat","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","value":"MBSCipherError"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MBSCipherError"}],"op":"replace"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","op":"replace","value":[{"text":"MBSCipherError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1unsupportedFormat\/title","value":"MBSCipherErrorUnsupportedFormat","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1unsupportedFormat\/fragments","value":[{"text":"MBSCipherErrorUnsupportedFormat","kind":"identifier"}]}]}]}