{"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bufferAllocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct","preciseIdentifier":"s:SC14MBSRandomErrorLeV","text":"MBSRandomError"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@MBSRandomError","text":"Code","kind":"typeIdentifier","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/bufferAllocation","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/bufferallocation"]}],"metadata":{"title":"bufferAllocation","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bufferAllocation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SC14MBSRandomErrorLeV","text":"MBSRandomError"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Code","preciseIdentifier":"c:@E@MBSRandomError"}],"externalID":"s:SC14MBSRandomErrorLeV16bufferAllocationSoAAVvpZ","platforms":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"15.6","unavailable":false},{"name":"iPadOS","introducedAt":"15.6","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"15.6","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"}],"role":"symbol","symbolKind":"property","modules":[{"name":"MbSecureCrypto"}],"roleHeading":"Type Property"},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSRandomError","kind":"identifier"}],"title":"MBSRandomError","navigatorTitle":[{"text":"MBSRandomError","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/bufferAllocation":{"title":"bufferAllocation","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/bufferallocation","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bufferAllocation"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SC14MBSRandomErrorLeV","kind":"typeIdentifier","text":"MBSRandomError"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@MBSRandomError","kind":"typeIdentifier","text":"Code"}],"kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/bufferAllocation"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"navigatorTitle":[{"text":"Code","kind":"identifier"}],"title":"MBSRandomError.Code","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","abstract":[{"type":"text","text":"Error codes for Random operations."}],"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","title":"MbSecureCrypto","role":"collection","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title","value":"MBSRandomError","op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MBSRandomError"}],"op":"replace"},{"value":[{"text":"MBSRandomError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle"}]}]}