{"sections":[],"topicSections":[{"anchor":"Error-Handling","title":"Error Handling","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]},{"generated":true,"anchor":"Classes","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge"],"title":"Classes"},{"anchor":"Structures","generated":true,"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct"],"title":"Structures"},{"generated":true,"title":"Variables","anchor":"Variables","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSErrorDomain","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/kMBSCipherMaxFileSize"]},{"title":"Enumerations","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat"],"anchor":"Enumerations","generated":true}],"metadata":{"role":"collection","modules":[{"name":"MbSecureCrypto"}],"roleHeading":"Framework","title":"MbSecureCrypto","symbolKind":"module","externalID":"MbSecureCrypto"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto"},"abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"primaryContentSections":[{"kind":"content","content":[{"text":"Table of Contents","level":2,"anchor":"Table-of-Contents","type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"#overview"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"#aes-gcm","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"#format-specifications","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"#types-and-algorithms"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"#error-handling","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"#usage-notes","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"#best-practices","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"#version-history","isActive":true,"type":"reference"}]}]}]},{"type":"heading","anchor":"Overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"MbSecureCrypto provides cryptographically secure random number generation and encryption capabilities.","type":"text"}]},{"level":2,"anchor":"AES-GCM","text":"AES-GCM","type":"heading"},{"anchor":"AES-GCM-Implementation-Details","level":3,"text":"AES-GCM Implementation Details","type":"heading"},{"level":4,"type":"heading","anchor":"Nonce-and-Tag-Handling","text":"Nonce and Tag Handling"},{"inlineContent":[{"text":"The ","type":"text"},{"code":"MBSCipher","type":"codeVoice"},{"type":"text","text":" class automatically handles nonces and authentication tags:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"Nonce Generation"}],"type":"strong"},{"text":": Each encryption operation generates a fresh 12-byte nonce using ","type":"text"},{"code":"MBSRandom","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Data Format"}]},{"type":"text","text":": Encrypted output is structured as "},{"code":"[nonce][ciphertext][tag]","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Sizing"}],"type":"strong"},{"type":"text","text":":"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Nonce: 12 bytes"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Tag: 16 bytes","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Minimum total size: 28 bytes (even for empty input)","type":"text"}]}]}],"type":"unorderedList"}]}]},{"level":4,"anchor":"Format-Details","text":"Format Details","type":"heading"},{"syntax":"objc","code":["\/\/ Encryption result structure","typedef struct {","    uint8_t nonce[12];     \/\/ Random nonce","    uint8_t ciphertext[];  \/\/ Encrypted data (variable length)","    uint8_t tag[16];       \/\/ Authentication tag","} MBSEncryptedData;"],"type":"codeListing"},{"inlineContent":[{"type":"text","text":"The decryption functions automatically extract and validate these components, ensuring authenticated decryption."}],"type":"paragraph"},{"text":"Format Specifications","anchor":"Format-Specifications","type":"heading","level":2},{"inlineContent":[{"text":"Format V0 (Default)","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Used in versions 0.3.0 and earlier"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The V0 format is structured as follows:"}]},{"type":"codeListing","syntax":null,"code":["[12-byte nonce][ciphertext][16-byte tag]"]},{"type":"paragraph","inlineContent":[{"text":"Key characteristics:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Nonce: 12 bytes, randomly generated","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Total overhead: 28 bytes per encrypted output","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Base64 encoded for string operations"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Raw bytes for data\/file operations","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"No explicit version or algorithm indicators"}],"type":"paragraph"}]}],"type":"unorderedList"},{"text":"Types and Algorithms","level":2,"type":"heading","anchor":"Types-and-Algorithms"},{"anchor":"MBSCipherAlgorithm","type":"heading","level":3,"text":"MBSCipherAlgorithm"},{"syntax":"objectivec","type":"codeListing","code":["typedef NS_ENUM(NSInteger, MBSCipherAlgorithm) {","    MBSCipherAlgorithmAESGCM = 0","} API_AVAILABLE(macos(12.4), ios(15.6));"]},{"level":3,"text":"MBSCipherFormat","type":"heading","anchor":"MBSCipherFormat"},{"code":["typedef NS_ENUM(uint8_t, MBSCipherFormat) {","    \/\/\/ Format V0: [12B nonce][ciphertext][16B tag]","    MBSCipherFormatV0 = 0","} API_AVAILABLE(macos(12.4), ios(15.6));"],"syntax":"objectivec","type":"codeListing"},{"text":"Error Handling","type":"heading","anchor":"Error-Handling","level":2},{"level":3,"type":"heading","anchor":"Random-Operation-Errors-MBSRandomError","text":"Random Operation Errors (MBSRandomError)"},{"type":"codeListing","code":["typedef NS_ERROR_ENUM(MBSErrorDomain, MBSRandomError) {","    MBSRandomErrorInvalidByteCount = 100,","    MBSRandomErrorGenerationFailed = 101,","    MBSRandomErrorBufferAllocation = 102","};"],"syntax":"objectivec"},{"text":"Cipher Operation Errors","level":3,"type":"heading","anchor":"Cipher-Operation-Errors"},{"code":["typedef NS_ERROR_ENUM(MBSErrorDomain, MBSCipherError) {","    \/\/ Input validation errors","    MBSCipherErrorInvalidKey = 200,           \/\/ Key size doesn't match algorithm requirements","    MBSCipherErrorInvalidIV = 201,            \/\/ IV\/nonce is invalid or wrong size","    MBSCipherErrorInvalidInput = 202,         \/\/ Input data is invalid or corrupted","    MBSCipherErrorUnsupportedAlgorithm = 203, \/\/ Requested algorithm is not supported","    MBSCipherErrorUnsupportedFormat = 204,    \/\/ Unknown or unsupported format version","    MBSCipherErrorFormatDetectionFailed = 205, \/\/ Failed to detect format version","    MBSCipherErrorFormatMismatch = 206,       \/\/ Format version mismatch during decryption","    ","    \/\/ Operation errors","    MBSCipherErrorEncryptionFailed = 210,     \/\/ Encryption operation failed","    MBSCipherErrorDecryptionFailed = 211,     \/\/ Decryption operation failed","    MBSCipherErrorAuthenticationFailed = 212,  \/\/ Authentication tag verification failed","    ","    \/\/ File operation errors","    MBSCipherErrorIOFailure = 220,            \/\/ File read\/write operation failed","    MBSCipherErrorFileTooLarge = 221,         \/\/ File exceeds size limit","    MBSCipherErrorFilePermission = 222        \/\/ Insufficient permission to access file","};"],"syntax":"objectivec","type":"codeListing"},{"text":"Usage Notes","type":"heading","level":2,"anchor":"Usage-Notes"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"Format parameter is optional, defaults to V0","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"When decrypting, format detection is automatic if not specified","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Encrypted output includes format version, nonce, and authentication tag"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"All operations maintain backward compatibility"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Maximum file size limit: 10MB"}]}]}]},{"text":"Best Practices","anchor":"Best-Practices","level":2,"type":"heading"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Key Management"}]}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Generate keys using ","type":"text"},{"type":"codeVoice","code":"MBSRandom generateBytes:error:"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Store keys securely in Keychain"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use unique keys for each encryption operation"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement proper key rotation"}]}]}]}]},{"content":[{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Memory Security"}]}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Zero sensitive data after use"}]}]},{"content":[{"inlineContent":[{"text":"Use autoreleasepool for deterministic cleanup","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Avoid logging sensitive information"}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Error Handling"}]}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Always check error return values"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Handle all error cases appropriately","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Avoid exposing sensitive information in errors"}]}]}]}]},{"content":[{"inlineContent":[{"inlineContent":[{"type":"text","text":"File Operations"}],"type":"strong"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Respect the 10MB file size limit"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Use atomic file operations"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Clean up temporary files"}]}]}],"type":"unorderedList"}]}]},{"type":"heading","level":2,"anchor":"Version-History","text":"Version History"},{"text":"Version 0.4.0","anchor":"Version-040","type":"heading","level":3},{"text":"Added","type":"heading","anchor":"Added","level":4},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Format versioning support via "},{"code":"MBSCipherFormat","type":"codeVoice"},{"type":"text","text":" enum"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"New API methods with explicit format parameters"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Improved interoperability documentation"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Format versioning documentation","type":"text"}]}]}]},{"level":4,"anchor":"Changed","text":"Changed","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Enhanced error messages for format-related issues","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Updated documentation with format specifications","type":"text"}]}]}]},{"anchor":"Compatibility","level":4,"type":"heading","text":"Compatibility"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Fully backward compatible with 0.3.0"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Default format (V0) matches existing implementation"}]}]}],"type":"unorderedList"},{"anchor":"Version-030","text":"Version 0.3.0","type":"heading","level":3},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Added encryption capabilities","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Added MBSRandom class","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added comprehensive error handling"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Deprecated MBSCryptoOperation"}],"type":"paragraph"}]}]},{"level":3,"text":"Version 0.2.0","type":"heading","anchor":"Version-020"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Added random bytes generation methods"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Added hex and base64 encoding options","type":"text"}]}]}]},{"type":"heading","text":"Version 0.1.0","level":3,"anchor":"Version-010"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Initial release","type":"text"}],"type":"paragraph"}]}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[[]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto"]}],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","kind":"symbol","type":"topic","navigatorTitle":[{"text":"Code","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","abstract":[{"text":"Error codes for Random operations.","type":"text"}],"title":"MBSRandomError.Code","role":"symbol"},"#usage-notes":{"type":"link","titleInlineContent":[{"type":"text","text":"Usage Notes"}],"title":"Usage Notes","url":"#usage-notes","identifier":"#usage-notes"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipher":{"kind":"symbol","fragments":[{"kind":"identifier","text":"MBSCipher"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher","abstract":[{"text":"A secure encryption and decryption utility that implements authenticated encryption.","type":"text"}],"url":"\/documentation\/mbsecurecrypto\/mbscipher","role":"symbol","type":"topic","title":"MBSCipher"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"role":"collection","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"type":"topic","kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto"},"#version-history":{"identifier":"#version-history","type":"link","title":"Version History","titleInlineContent":[{"type":"text","text":"Version History"}],"url":"#version-history"},"#error-handling":{"identifier":"#error-handling","type":"link","title":"Error Handling","titleInlineContent":[{"type":"text","text":"Error Handling"}],"url":"#error-handling"},"#overview":{"identifier":"#overview","type":"link","title":"Overview","titleInlineContent":[{"type":"text","text":"Overview"}],"url":"#overview"},"#aes-gcm":{"identifier":"#aes-gcm","type":"link","title":"AES-GCM","titleInlineContent":[{"type":"text","text":"AES-GCM"}],"url":"#aes-gcm"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MbSecureCryptoVersionString":{"fragments":[{"kind":"identifier","text":"MbSecureCryptoVersionString"}],"title":"MbSecureCryptoVersionString","kind":"symbol","type":"topic","abstract":[{"text":"Project version string","type":"text"}],"url":"\/documentation\/mbsecurecrypto\/mbsecurecryptoversionstring","role":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MbSecureCryptoVersionString"},"#format-specifications":{"identifier":"#format-specifications","type":"link","title":"Format Specifications","titleInlineContent":[{"type":"text","text":"Format Specifications"}],"url":"#format-specifications"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSErrorDomain":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBSErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSErrorDomain","navigatorTitle":[{"text":"MBSErrorDomain","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","title":"MBSErrorDomain","url":"\/documentation\/mbsecurecrypto\/mbserrordomain"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/kMBSCipherMaxFileSize":{"type":"topic","navigatorTitle":[{"text":"kMBSCipherMaxFileSize","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"kMBSCipherMaxFileSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"url":"\/documentation\/mbsecurecrypto\/kmbsciphermaxfilesize","title":"kMBSCipherMaxFileSize","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/kMBSCipherMaxFileSize","role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct":{"url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBSRandomError"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBSRandomError"}],"abstract":[],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct","title":"MBSRandomError","role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge":{"abstract":[],"role":"symbol","kind":"symbol","title":"MBSCipherBridge","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherBridge","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MBSCipherBridge","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherbridge"},"#types-and-algorithms":{"identifier":"#types-and-algorithms","type":"link","title":"Types & Algorithms","titleInlineContent":[{"type":"text","text":"Types & Algorithms"}],"url":"#types-and-algorithms"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MbSecureCryptoVersionNumber":{"type":"topic","fragments":[{"kind":"identifier","text":"MbSecureCryptoVersionNumber"}],"url":"\/documentation\/mbsecurecrypto\/mbsecurecryptoversionnumber","title":"MbSecureCryptoVersionNumber","kind":"symbol","abstract":[{"text":"Project version number","type":"text"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MbSecureCryptoVersionNumber","role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandom":{"type":"topic","fragments":[{"kind":"identifier","text":"MBSRandom"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandom","kind":"symbol","abstract":[{"text":"A utility class that provides cryptographically secure random number generation.","type":"text"}],"role":"symbol","title":"MBSRandom","url":"\/documentation\/mbsecurecrypto\/mbsrandom"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"role":"symbol","title":"MBSCipherError.Code","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","abstract":[{"text":"Error codes for cipher operations","type":"text"}],"kind":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"kind":"symbol","navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"identifier"}],"abstract":[],"title":"MBSCipherAlgorithm","role":"symbol"},"#best-practices":{"identifier":"#best-practices","type":"link","title":"Best Practices","titleInlineContent":[{"type":"text","text":"Best Practices"}],"url":"#best-practices"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherFormat":{"kind":"symbol","title":"MBSCipherFormat","navigatorTitle":[{"kind":"identifier","text":"MBSCipherFormat"}],"type":"topic","abstract":[{"text":"Supported ciphertext format versions","type":"text"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBSCipherFormat"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"MBSCipherError"}],"type":"topic","title":"MBSCipherError","abstract":[],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":[{"anchor":"Essentials","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandom","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipher"],"title":"Essentials"},{"anchor":"Error-Handling","title":"Error Handling","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]},{"title":"Classes","generated":true,"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge"],"anchor":"Classes"},{"title":"Variables","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSErrorDomain","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MbSecureCryptoVersionNumber","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MbSecureCryptoVersionString","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/kMBSCipherMaxFileSize"],"anchor":"Variables","generated":true},{"anchor":"Enumerations","title":"Enumerations","generated":true,"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat"]}],"op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"MBSRandomError","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title"},{"value":[{"kind":"identifier","text":"MBSRandomError"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MBSRandomError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSErrorDomain\/title","value":"MBSErrorDomain","op":"replace"},{"value":[{"text":"MBSErrorDomain","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSErrorDomain\/fragments","op":"replace"},{"value":"kMBSCipherMaxFileSize","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1kMBSCipherMaxFileSize\/title"},{"value":[{"text":"kMBSCipherMaxFileSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1kMBSCipherMaxFileSize\/fragments"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/title","value":"MBSCipherBridge","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherBridge"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/fragments"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/navigatorTitle","op":"replace","value":[{"text":"MBSCipherBridge","kind":"identifier"}]},{"value":"MBSCipherError","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title"},{"value":[{"kind":"identifier","text":"MBSCipherError"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","value":[{"text":"MBSCipherError","kind":"identifier"}]},{"op":"replace","value":"MBSCipherAlgorithm","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title"},{"op":"replace","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments"},{"value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/title","value":"MBSCipherFormat"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/fragments","value":[{"kind":"identifier","text":"MBSCipherFormat"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/navigatorTitle","value":[{"text":"MBSCipherFormat","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}