{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"encryptString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"algorithm"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm","text":"MBSCipherAlgorithm"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":"?>?) -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptString(_:key:algorithm:error:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encryptString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"algorithm","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm","text":"MBSCipherAlgorithm"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":"?>?) -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"roleHeading":"Type Method","role":"symbol","externalID":"c:@M@MbSecureCrypto@objc(cs)MBSCipherBridge(cm)encryptString:key:algorithm:error:","modules":[{"name":"MbSecureCrypto"}],"title":"encryptString(_:key:algorithm:error:)","symbolKind":"method","navigatorTitle":[{"text":"encryptString:key:algorithm:error:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptstring(_:key:algorithm:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptstring(_:key:algorithm:error:)"]}],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","title":"MbSecureCrypto","role":"collection","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSCipherAlgorithm"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","title":"MBSCipherAlgorithm","navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/encryptString(_:key:algorithm:error:)":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptString(_:key:algorithm:error:)","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptstring(_:key:algorithm:error:)","role":"symbol","title":"encryptString(_:key:algorithm:error:)","navigatorTitle":[{"text":"encryptString:key:algorithm:error:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"encryptString","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"algorithm","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MBSCipherAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":"?>?) -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge":{"url":"\/documentation\/mbsecurecrypto\/mbscipherbridge","kind":"symbol","type":"topic","title":"MBSCipherBridge","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MBSCipherBridge","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherBridge"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"encryptString:key:algorithm:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"encryptString:key:algorithm:error:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"encryptString:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"string","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"key:"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":" "},{"text":"algorithm:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm","text":"MBSCipherAlgorithm"},{"kind":"text","text":") "},{"kind":"internalParam","text":"algorithm"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MBSCipherAlgorithm","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title"},{"value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptString(_:key:algorithm:error:)\/title","value":"encryptString:key:algorithm:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptString(_:key:algorithm:error:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"encryptString:key:algorithm:error:","kind":"identifier"}]},{"op":"replace","value":"MBSCipherBridge","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/fragments","value":[{"kind":"identifier","text":"MBSCipherBridge"}]},{"value":[{"text":"MBSCipherBridge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/navigatorTitle","op":"replace"}]}]}