{"kind":"symbol","abstract":[{"type":"text","text":"AES-GCM"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/AESGCM"},"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AESGCM","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipheralgorithm\/aesgcm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipheralgorithm\/aesgcm"]}],"metadata":{"externalID":"c:@E@MBSCipherAlgorithm@MBSCipherAlgorithmAESGCM","symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"AESGCM","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherAlgorithmAESGCM"}],"modules":[{"name":"MbSecureCrypto"}],"role":"symbol","platforms":[{"introducedAt":"15.6","unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"beta":false,"name":"iPadOS","introducedAt":"15.6","unavailable":false,"deprecated":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"15.6","unavailable":false,"deprecated":false}],"title":"MBSCipherAlgorithm.AESGCM"},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm/AESGCM":{"abstract":[{"type":"text","text":"AES-GCM"}],"title":"MBSCipherAlgorithm.AESGCM","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/AESGCM","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AESGCM"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherAlgorithmAESGCM"}],"url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm\/aesgcm"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"title":"MBSCipherAlgorithm","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBSCipherAlgorithm","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"kind":"symbol","abstract":[{"text":"Supported Cipher Algorithms","type":"text"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"url":"\/documentation\/mbsecurecrypto","title":"MbSecureCrypto","kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MBSCipherAlgorithmAESGCM","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBSCipherAlgorithmAESGCM"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MBSCipherAlgorithmAESGCM","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"MBSCipherAlgorithmAESGCM","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm~1AESGCM\/title"},{"value":[{"text":"MBSCipherAlgorithmAESGCM","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm~1AESGCM\/fragments"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","value":"MBSCipherAlgorithm","op":"replace"},{"value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}