{"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm"]]},"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/init(rawValue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"platforms":[{"name":"iOS","beta":false,"introducedAt":"15.6","deprecated":false,"unavailable":false},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"15.6"},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"15.6","unavailable":false}],"roleHeading":"Initializer","role":"symbol","symbolKind":"init","modules":[{"name":"MbSecureCrypto"}],"title":"init(rawValue:)","externalID":"s:So18MBSCipherAlgorithmV8rawValueABSgSi_tcfc","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipheralgorithm\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"type":"topic","title":"MBSCipherAlgorithm","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"abstract":[],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"identifier"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm\/init(rawValue:)"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","type":"topic","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}],"title":"MbSecureCrypto","kind":"symbol","url":"\/documentation\/mbsecurecrypto","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","op":"replace","value":"MBSCipherAlgorithm"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"op":"replace"},{"value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","op":"replace"}]}]}