{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"V1","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat"]]},"metadata":{"title":"MBSCipherFormat.V1","platforms":[{"deprecated":false,"introducedAt":"15.6","beta":false,"name":"iOS","unavailable":false},{"beta":false,"introducedAt":"15.6","deprecated":false,"name":"iPadOS","unavailable":false},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"15.6"}],"role":"symbol","externalID":"c:@E@MBSCipherFormat@MBSCipherFormatV1","modules":[{"name":"MbSecureCrypto"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"V1"}],"roleHeading":"Case","navigatorTitle":[{"text":"MBSCipherFormatV1","kind":"identifier"}],"symbolKind":"case"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherformat\/v1"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherformat\/v1"]}],"abstract":[{"text":"Reserved for future use","type":"text"}],"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/V1","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherFormat/V1":{"url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/v1","navigatorTitle":[{"text":"MBSCipherFormatV1","kind":"identifier"}],"title":"MBSCipherFormat.V1","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/V1","abstract":[{"type":"text","text":"Reserved for future use"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"V1","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherFormat":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MBSCipherFormat"}],"title":"MBSCipherFormat","url":"\/documentation\/mbsecurecrypto\/mbscipherformat","type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSCipherFormat"}],"abstract":[{"type":"text","text":"Supported ciphertext format versions"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","title":"MbSecureCrypto","role":"collection","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MBSCipherFormatV1","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"MBSCipherFormatV1"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBSCipherFormatV1","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MBSCipherFormatV1","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat~1V1\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat~1V1\/fragments","value":[{"text":"MBSCipherFormatV1","kind":"identifier"}]},{"op":"replace","value":"MBSCipherFormat","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherFormat"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/fragments"},{"value":[{"text":"MBSCipherFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/navigatorTitle"}]}]}