{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/bufferAllocation"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/bufferallocation"]},{"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/bufferallocation"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code"]]},"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferAllocation"}],"modules":[{"name":"MbSecureCrypto"}],"role":"symbol","externalID":"c:@E@MBSRandomError@MBSRandomErrorBufferAllocation","title":"MBSRandomError.Code.bufferAllocation","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MBSRandomErrorBufferAllocation"}],"platforms":[{"introducedAt":"15.6","deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"15.6","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"15.6","deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"bufferAllocation","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/bufferAllocation":{"url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/bufferallocation","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bufferAllocation"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/bufferAllocation","title":"MBSRandomError.Code.bufferAllocation","navigatorTitle":[{"text":"MBSRandomErrorBufferAllocation","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"kind":"symbol","url":"\/documentation\/mbsecurecrypto","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic","abstract":[{"text":"A secure cryptography library for iOS and macOS.","type":"text"}],"title":"MbSecureCrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","kind":"symbol","abstract":[{"type":"text","text":"Error codes for Random operations."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"Code","kind":"identifier"}],"title":"MBSRandomError.Code"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"MBSRandomErrorBufferAllocation","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBSRandomErrorBufferAllocation"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MBSRandomErrorBufferAllocation","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1bufferAllocation\/title","value":"MBSRandomErrorBufferAllocation","op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1bufferAllocation\/fragments","value":[{"text":"MBSRandomErrorBufferAllocation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title","value":"MBSRandomError"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments","op":"replace","value":[{"text":"MBSRandomError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle","value":[{"kind":"identifier","text":"MBSRandomError"}]}]}]}