{"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/Equatable-Implementations","interfaceLanguage":"swift"},"metadata":{"role":"collectionGroup","modules":[{"name":"MbSecureCrypto"}],"roleHeading":"API Collection","title":"Equatable Implementations"},"topicSections":[{"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/!=(_:_:)"],"generated":true,"title":"Operators","anchor":"Operators"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code"]]},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/!=(_:_:)":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/!=(_:_:)","role":"symbol","title":"!=(_:_:)","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[],"kind":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"title":"MBSRandomError.Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","abstract":[{"text":"Error codes for Random operations.","type":"text"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"type":"topic"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","type":"topic","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBSRandomError","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments","value":[{"text":"MBSRandomError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle","op":"replace","value":[{"text":"MBSRandomError","kind":"identifier"}]}]}]}