{"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/generationFailed","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generationFailed"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/generationfailed"]},{"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/generationfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","externalID":"c:@E@MBSRandomError@MBSRandomErrorGenerationFailed","platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"15.6","unavailable":false},{"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"15.6","deprecated":false},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"15.6","name":"Mac Catalyst"}],"navigatorTitle":[{"text":"MBSRandomErrorGenerationFailed","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generationFailed"}],"modules":[{"name":"MbSecureCrypto"}],"role":"symbol","title":"MBSRandomError.Code.generationFailed","symbolKind":"case"},"sections":[],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/generationFailed":{"kind":"symbol","abstract":[],"type":"topic","title":"MBSRandomError.Code.generationFailed","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/generationFailed","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/generationfailed","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generationFailed"}],"navigatorTitle":[{"text":"MBSRandomErrorGenerationFailed","kind":"identifier"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","role":"collection","type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"role":"symbol","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Code"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","abstract":[{"type":"text","text":"Error codes for Random operations."}],"title":"MBSRandomError.Code","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBSRandomErrorGenerationFailed","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBSRandomErrorGenerationFailed"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"MBSRandomErrorGenerationFailed","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1generationFailed\/title","op":"replace","value":"MBSRandomErrorGenerationFailed"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1generationFailed\/fragments","op":"replace","value":[{"text":"MBSRandomErrorGenerationFailed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title","value":"MBSRandomError","op":"replace"},{"value":[{"text":"MBSRandomError","kind":"identifier"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MBSRandomError"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle"}]}]}