{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/hashvalue"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/hashValue"},"metadata":{"modules":[{"name":"MbSecureCrypto","relatedModules":["Swift"]}],"role":"symbol","roleHeading":"Instance Property","extendedModule":"Swift","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@E@MBSRandomError","title":"hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"symbolKind":"property","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]}},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"type":"text","text":"."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/RawRepresentable-Implementations"]]},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/RawRepresentable-Implementations":{"type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/RawRepresentable-Implementations","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/rawrepresentable-implementations","abstract":[]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/hashValue":{"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/hashvalue","role":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/hashValue","type":"topic","abstract":[],"title":"hashValue"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","kind":"symbol","type":"topic","navigatorTitle":[{"text":"Code","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","abstract":[{"text":"Error codes for Random operations.","type":"text"}],"title":"MBSRandomError.Code","role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"role":"collection","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"type":"topic","kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title","value":"MBSRandomError"},{"value":[{"text":"MBSRandomError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments"},{"value":[{"text":"MBSRandomError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}