{"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/RawRepresentable-Implementations"]]},"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/hash(into:)","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"MbSecureCrypto"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@E@MBSRandomError","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"hash(into:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/RawRepresentable-Implementations":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/RawRepresentable-Implementations","kind":"article","abstract":[],"role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/rawrepresentable-implementations"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"abstract":[{"type":"text","text":"Error codes for Random operations."}],"title":"MBSRandomError.Code","navigatorTitle":[{"kind":"identifier","text":"Code"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","type":"topic","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}],"title":"MbSecureCrypto","kind":"symbol","url":"\/documentation\/mbsecurecrypto","role":"collection"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/hash(into:)":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/hash(into:)","kind":"symbol","abstract":[],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"hash(into:)","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/hash(into:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBSRandomError","op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments","value":[{"text":"MBSRandomError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle","value":[{"text":"MBSRandomError","kind":"identifier"}]}]}]}