{"sections":[],"metadata":{"modules":[{"name":"MbSecureCrypto"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"MBSRandomErrorInvalidByteCount","kind":"identifier"}],"title":"MBSRandomError.Code.invalidByteCount","externalID":"c:@E@MBSRandomError@MBSRandomErrorInvalidByteCount","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.6"},{"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"15.6","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"15.6","unavailable":false,"name":"Mac Catalyst"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidByteCount"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidByteCount"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/invalidbytecount"]},{"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/invalidbytecount"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/invalidByteCount","interfaceLanguage":"swift"},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","type":"topic","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","role":"collection","kind":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/invalidByteCount":{"title":"MBSRandomError.Code.invalidByteCount","abstract":[],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/invalidByteCount","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBSRandomErrorInvalidByteCount"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/invalidbytecount","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidByteCount","kind":"identifier"}],"role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"title":"MBSRandomError.Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","abstract":[{"text":"Error codes for Random operations.","type":"text"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MBSRandomErrorInvalidByteCount","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBSRandomErrorInvalidByteCount"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MBSRandomErrorInvalidByteCount"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1invalidByteCount\/title","op":"replace","value":"MBSRandomErrorInvalidByteCount"},{"value":[{"text":"MBSRandomErrorInvalidByteCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1invalidByteCount\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title","value":"MBSRandomError"},{"op":"replace","value":[{"kind":"identifier","text":"MBSRandomError"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments"},{"value":[{"text":"MBSRandomError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle"}]}]}