{"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/hashValue"],"title":"Instance Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/hash(into:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/rawrepresentable-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/RawRepresentable-Implementations"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code"]]},"metadata":{"roleHeading":"API Collection","title":"RawRepresentable Implementations","role":"collectionGroup","modules":[{"name":"MbSecureCrypto"}]},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","kind":"symbol","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"role":"collection","url":"\/documentation\/mbsecurecrypto","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","type":"topic"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/hash(into:)":{"abstract":[],"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/hash(into:)","role":"symbol","kind":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"title":"hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/hash(into:)"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"navigatorTitle":[{"text":"Code","kind":"identifier"}],"abstract":[{"type":"text","text":"Error codes for Random operations."}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","kind":"symbol","title":"MBSRandomError.Code"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/hashValue":{"abstract":[],"type":"topic","title":"hashValue","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"role":"symbol","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/hashvalue"}},"variantOverrides":[{"patch":[{"value":"MBSRandomError","op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MBSRandomError"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBSRandomError"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}