{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationFailed","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@MBSCipherError","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","text":"Code","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"authenticationFailed","roleHeading":"Type Property","modules":[{"name":"MbSecureCrypto"}],"externalID":"s:SC14MBSCipherErrorLeV20authenticationFailedSoAAVvpZ","role":"symbol","platforms":[{"deprecated":false,"beta":false,"introducedAt":"15.6","name":"iOS","unavailable":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"15.6","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.6"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationFailed"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@MBSCipherError","text":"Code","kind":"typeIdentifier"}],"symbolKind":"property"},"kind":"symbol","identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/authenticationFailed","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/authenticationfailed"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct"]]},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct":{"title":"MBSCipherError","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherError"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/authenticationFailed":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationFailed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError"},{"kind":"text","text":"."},{"text":"Code","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherError"}],"abstract":[],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/authenticationfailed","title":"authenticationFailed","kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/authenticationFailed","role":"symbol","type":"topic"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","title":"MBSCipherError.Code","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","role":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","abstract":[{"text":"Error codes for cipher operations","type":"text"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"url":"\/documentation\/mbsecurecrypto","title":"MbSecureCrypto","kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","value":"MBSCipherError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","value":[{"text":"MBSCipherError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","value":[{"text":"MBSCipherError","kind":"identifier"}]}]}]}