{"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/authenticationFailed","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/decryptionFailed","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/encryptionFailed","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/filePermission","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/fileTooLarge","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/formatDetectionFailed","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/formatMismatch","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidIV","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidInput","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidKey","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/ioFailure","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/unsupportedAlgorithm","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/unsupportedFormat"],"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/Equatable-Implementations","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"},"sections":[],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/s15BitwiseCopyableP","doc:\/\/com.mavbozo.mbsecurecrypto\/SQ","doc:\/\/com.mavbozo.mbsecurecrypto\/SH","doc:\/\/com.mavbozo.mbsecurecrypto\/SY","doc:\/\/com.mavbozo.mbsecurecrypto\/s8SendableP"],"type":"conformsTo"}],"seeAlsoSections":[{"title":"Error Handling","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code"],"generated":true,"anchor":"Error-Handling"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Error codes for cipher operations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code"]}],"metadata":{"symbolKind":"enum","platforms":[{"introducedAt":"15.6","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"15.6"},{"introducedAt":"15.6","unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false}],"role":"symbol","modules":[{"name":"MbSecureCrypto"}],"title":"MBSCipherError.Code","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"externalID":"c:@E@MBSCipherError","navigatorTitle":[{"kind":"identifier","text":"Code"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto"]]},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/invalidIV":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidIV","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/invalidiv","role":"symbol","navigatorTitle":[{"text":"MBSCipherErrorInvalidIV","kind":"identifier"}],"title":"MBSCipherError.Code.invalidIV","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidIV","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/SQ","title":"Swift.Equatable"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/encryptionFailed":{"navigatorTitle":[{"text":"MBSCipherErrorEncryptionFailed","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/encryptionFailed","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/encryptionfailed","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"encryptionFailed","kind":"identifier"}],"title":"MBSCipherError.Code.encryptionFailed","abstract":[],"kind":"symbol","role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/s8SendableP","title":"Swift.Sendable"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/init(rawValue:)":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/init(rawValue:)","kind":"symbol","type":"topic","title":"init(rawValue:)","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/init(rawvalue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/Equatable-Implementations":{"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/Equatable-Implementations","type":"topic","kind":"article","abstract":[],"title":"Equatable Implementations"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/formatMismatch":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formatMismatch"}],"kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/formatMismatch","role":"symbol","navigatorTitle":[{"text":"MBSCipherErrorFormatMismatch","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/formatmismatch","title":"MBSCipherError.Code.formatMismatch","type":"topic"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/fileTooLarge":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/fileTooLarge","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/filetoolarge","title":"MBSCipherError.Code.fileTooLarge","role":"symbol","navigatorTitle":[{"text":"MBSCipherErrorFileTooLarge","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileTooLarge","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/decryptionFailed":{"title":"MBSCipherError.Code.decryptionFailed","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/decryptionfailed","abstract":[],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/decryptionFailed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"decryptionFailed","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorDecryptionFailed"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/unsupportedFormat":{"navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorUnsupportedFormat"}],"title":"MBSCipherError.Code.unsupportedFormat","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/unsupportedformat","type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/unsupportedFormat","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unsupportedFormat","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/invalidInput":{"navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorInvalidInput"}],"type":"topic","abstract":[],"kind":"symbol","title":"MBSCipherError.Code.invalidInput","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/invalidinput","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidInput","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidInput","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"role":"collection","type":"topic","kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS.","type":"text"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto"},"doc://com.mavbozo.mbsecurecrypto/SH":{"type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/SH","title":"Swift.Hashable"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/RawRepresentable-Implementations","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"kind":"article","type":"topic"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/unsupportedAlgorithm":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unsupportedAlgorithm","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/unsupportedAlgorithm","navigatorTitle":[{"text":"MBSCipherErrorUnsupportedAlgorithm","kind":"identifier"}],"title":"MBSCipherError.Code.unsupportedAlgorithm","role":"symbol","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/unsupportedalgorithm","abstract":[],"type":"topic"},"doc://com.mavbozo.mbsecurecrypto/SY":{"type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/SY","title":"Swift.RawRepresentable"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"role":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","title":"MBSCipherError.Code","abstract":[{"text":"Error codes for cipher operations","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}],"kind":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/invalidKey":{"role":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/invalidkey","abstract":[],"title":"MBSCipherError.Code.invalidKey","navigatorTitle":[{"text":"MBSCipherErrorInvalidKey","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidKey","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidKey"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/ioFailure":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ioFailure"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorIOFailure"}],"role":"symbol","title":"MBSCipherError.Code.ioFailure","type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/ioFailure","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/iofailure"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/formatDetectionFailed":{"title":"MBSCipherError.Code.formatDetectionFailed","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/formatdetectionfailed","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"formatDetectionFailed","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherErrorFormatDetectionFailed"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/formatDetectionFailed"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","role":"symbol","abstract":[{"type":"text","text":"Error codes for Random operations."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","title":"MBSRandomError.Code","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/filePermission":{"title":"MBSCipherError.Code.filePermission","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/filepermission","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"MBSCipherErrorFilePermission","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"filePermission","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/filePermission","role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code/authenticationFailed":{"abstract":[],"navigatorTitle":[{"text":"MBSCipherErrorAuthenticationFailed","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code\/authenticationfailed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"authenticationFailed","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/authenticationFailed","type":"topic","role":"symbol","kind":"symbol","title":"MBSCipherError.Code.authenticationFailed"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"introducedAt":"15.6","unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"15.6"},{"introducedAt":"15.6","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"}],"path":"\/metadata\/platforms","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"MBSCipherError","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBSCipherError"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MBSCipherError","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/authenticationFailed","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/decryptionFailed","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/encryptionFailed","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/filePermission","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/fileTooLarge","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/formatDetectionFailed","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/formatMismatch","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidIV","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidInput","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/invalidKey","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/ioFailure","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/unsupportedAlgorithm","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code\/unsupportedFormat"],"generated":true,"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code"],"title":"Error Handling","generated":true,"anchor":"Error-Handling"}],"op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBSCipherError","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1invalidIV\/title","value":"MBSCipherErrorInvalidIV"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1invalidIV\/fragments","op":"replace","value":[{"text":"MBSCipherErrorInvalidIV","kind":"identifier"}]},{"op":"replace","value":"MBSCipherErrorEncryptionFailed","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1encryptionFailed\/title"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1encryptionFailed\/fragments","op":"replace","value":[{"text":"MBSCipherErrorEncryptionFailed","kind":"identifier"}]},{"op":"replace","value":"MBSCipherErrorFormatMismatch","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1formatMismatch\/title"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1formatMismatch\/fragments","op":"replace","value":[{"text":"MBSCipherErrorFormatMismatch","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1fileTooLarge\/title","value":"MBSCipherErrorFileTooLarge","op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1fileTooLarge\/fragments","value":[{"text":"MBSCipherErrorFileTooLarge","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1decryptionFailed\/title","value":"MBSCipherErrorDecryptionFailed"},{"value":[{"text":"MBSCipherErrorDecryptionFailed","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1decryptionFailed\/fragments","op":"replace"},{"value":"MBSCipherErrorUnsupportedFormat","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1unsupportedFormat\/title"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1unsupportedFormat\/fragments","op":"replace","value":[{"text":"MBSCipherErrorUnsupportedFormat","kind":"identifier"}]},{"value":"MBSCipherErrorInvalidInput","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1invalidInput\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MBSCipherErrorInvalidInput"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1invalidInput\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1unsupportedAlgorithm\/title","value":"MBSCipherErrorUnsupportedAlgorithm"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1unsupportedAlgorithm\/fragments","value":[{"text":"MBSCipherErrorUnsupportedAlgorithm","kind":"identifier"}],"op":"replace"},{"value":"MBSCipherError","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","op":"replace"},{"value":[{"text":"MBSCipherError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherError"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle"},{"value":"MBSCipherErrorInvalidKey","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1invalidKey\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1invalidKey\/fragments","value":[{"kind":"identifier","text":"MBSCipherErrorInvalidKey"}]},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1ioFailure\/title","op":"replace","value":"MBSCipherErrorIOFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1ioFailure\/fragments","value":[{"kind":"identifier","text":"MBSCipherErrorIOFailure"}]},{"value":"MBSCipherErrorFormatDetectionFailed","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1formatDetectionFailed\/title"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1formatDetectionFailed\/fragments","value":[{"text":"MBSCipherErrorFormatDetectionFailed","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title","op":"replace","value":"MBSRandomError"},{"value":[{"kind":"identifier","text":"MBSRandomError"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle","value":[{"text":"MBSRandomError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1filePermission\/title","value":"MBSCipherErrorFilePermission"},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherErrorFilePermission"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1filePermission\/fragments"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1authenticationFailed\/title","op":"replace","value":"MBSCipherErrorAuthenticationFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code~1authenticationFailed\/fragments","value":[{"text":"MBSCipherErrorAuthenticationFailed","kind":"identifier"}]}]}]}