{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileTooLarge"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MBSCipherError","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","preciseIdentifier":"s:SC14MBSCipherErrorLeV"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@MBSCipherError","text":"Code","kind":"typeIdentifier","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/fileTooLarge"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct"]]},"sections":[],"metadata":{"role":"symbol","platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"15.6","deprecated":false},{"name":"iPadOS","deprecated":false,"introducedAt":"15.6","unavailable":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"15.6","deprecated":false}],"externalID":"s:SC14MBSCipherErrorLeV12fileTooLargeSoAAVvpZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fileTooLarge","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherError","text":"Code"}],"modules":[{"name":"MbSecureCrypto"}],"title":"fileTooLarge","symbolKind":"property","roleHeading":"Type Property"},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/filetoolarge"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"type":"topic","title":"MBSCipherError.Code","kind":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"abstract":[{"type":"text","text":"Error codes for cipher operations"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"url":"\/documentation\/mbsecurecrypto","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS.","type":"text"}],"title":"MbSecureCrypto","role":"collection"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct":{"navigatorTitle":[{"text":"MBSCipherError","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","type":"topic","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MBSCipherError","kind":"identifier"}],"role":"symbol","title":"MBSCipherError","abstract":[]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/fileTooLarge":{"kind":"symbol","title":"fileTooLarge","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fileTooLarge"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError"},{"text":".","kind":"text"},{"text":"Code","preciseIdentifier":"c:@E@MBSCipherError","kind":"typeIdentifier"}],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/filetoolarge","role":"symbol","type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/fileTooLarge"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","value":"MBSCipherError"},{"value":[{"text":"MBSCipherError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","value":[{"text":"MBSCipherError","kind":"identifier"}]}]}]}