{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct"]]},"metadata":{"title":"formatMismatch","role":"symbol","symbolKind":"property","modules":[{"name":"MbSecureCrypto"}],"externalID":"s:SC14MBSCipherErrorLeV14formatMismatchSoAAVvpZ","platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"15.6","deprecated":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"15.6","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"15.6","beta":false,"name":"Mac Catalyst"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"formatMismatch"},{"kind":"text","text":": "},{"text":"MBSCipherError","kind":"typeIdentifier","preciseIdentifier":"s:SC14MBSCipherErrorLeV"},{"text":".","kind":"text"},{"text":"Code","preciseIdentifier":"c:@E@MBSCipherError","kind":"typeIdentifier"}],"roleHeading":"Type Property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formatMismatch"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@MBSCipherError","kind":"typeIdentifier","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","text":"Code"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/formatmismatch"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/formatMismatch","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"url":"\/documentation\/mbsecurecrypto","title":"MbSecureCrypto","kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/formatMismatch":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formatMismatch"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Code","preciseIdentifier":"c:@E@MBSCipherError"}],"abstract":[],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/formatmismatch","title":"formatMismatch","kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/formatMismatch","role":"symbol","type":"topic"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","title":"MBSCipherError.Code","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","role":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"type":"topic","abstract":[{"text":"Error codes for cipher operations","type":"text"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct":{"title":"MBSCipherError","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherError"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","value":"MBSCipherError"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MBSCipherError"}],"op":"replace"},{"value":[{"text":"MBSCipherError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}