{"metadata":{"symbolKind":"property","modules":[{"name":"MbSecureCrypto"}],"platforms":[{"introducedAt":"15.6","deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"unavailable":false,"introducedAt":"15.6","deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"15.6","name":"Mac Catalyst"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidInput","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MBSCipherError","kind":"typeIdentifier","preciseIdentifier":"s:SC14MBSCipherErrorLeV"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@MBSCipherError","kind":"typeIdentifier","text":"Code"}],"role":"symbol","title":"invalidInput","roleHeading":"Type Property","externalID":"s:SC14MBSCipherErrorLeV12invalidInputSoAAVvpZ"},"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"invalidInput","kind":"identifier"},{"kind":"text","text":": "},{"text":"MBSCipherError","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","preciseIdentifier":"s:SC14MBSCipherErrorLeV","kind":"typeIdentifier"},{"kind":"text","text":"."},{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","kind":"typeIdentifier","text":"Code","preciseIdentifier":"c:@E@MBSCipherError"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/invalidInput"},"sections":[],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/invalidinput"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","type":"topic","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}],"title":"MbSecureCrypto","kind":"symbol","url":"\/documentation\/mbsecurecrypto","role":"collection"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/invalidInput":{"type":"topic","title":"invalidInput","kind":"symbol","abstract":[],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/invalidInput","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/invalidinput","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidInput","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError"},{"text":".","kind":"text"},{"text":"Code","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherError"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"title":"MBSCipherError.Code","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Code"}],"abstract":[{"type":"text","text":"Error codes for cipher operations"}],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","type":"topic","abstract":[],"title":"MBSCipherError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBSCipherError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherError"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","value":"MBSCipherError"},{"value":[{"text":"MBSCipherError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments"},{"value":[{"text":"MBSCipherError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}