{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidIV"},{"kind":"text","text":": "},{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","text":"MBSCipherError","preciseIdentifier":"s:SC14MBSCipherErrorLeV","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Code","preciseIdentifier":"c:@E@MBSCipherError","kind":"typeIdentifier","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/invalidiv"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct"]]},"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/invalidIV","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidIV"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@MBSCipherError","text":"Code","kind":"typeIdentifier"}],"modules":[{"name":"MbSecureCrypto"}],"role":"symbol","externalID":"s:SC14MBSCipherErrorLeV9invalidIVSoAAVvpZ","platforms":[{"unavailable":false,"beta":false,"introducedAt":"15.6","name":"iOS","deprecated":false},{"name":"iPadOS","unavailable":false,"introducedAt":"15.6","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"15.6","name":"Mac Catalyst","beta":false,"deprecated":false}],"title":"invalidIV","symbolKind":"property"},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","title":"MBSCipherError.Code","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}],"role":"symbol","abstract":[{"type":"text","text":"Error codes for cipher operations"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct":{"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","kind":"symbol","title":"MBSCipherError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"MBSCipherError","kind":"identifier"}],"navigatorTitle":[{"text":"MBSCipherError","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"type":"topic","url":"\/documentation\/mbsecurecrypto","role":"collection","kind":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/invalidIV":{"role":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/invalidIV","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidIV"},{"text":": ","kind":"text"},{"text":"MBSCipherError","preciseIdentifier":"s:SC14MBSCipherErrorLeV","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@MBSCipherError","text":"Code","kind":"typeIdentifier"}],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/invalidiv","title":"invalidIV"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBSCipherError","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","value":[{"text":"MBSCipherError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherError"}],"op":"replace"}]}]}