{"kind":"symbol","sections":[],"metadata":{"title":"invalidKey","symbolKind":"property","role":"symbol","externalID":"s:SC14MBSCipherErrorLeV10invalidKeySoAAVvpZ","platforms":[{"introducedAt":"15.6","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"15.6"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"15.6"}],"modules":[{"name":"MbSecureCrypto"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherError","text":"Code"}],"roleHeading":"Type Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"invalidKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MBSCipherError","preciseIdentifier":"s:SC14MBSCipherErrorLeV","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct"},{"text":".","kind":"text"},{"text":"Code","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherError"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/invalidkey"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct"]]},"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/invalidKey","interfaceLanguage":"swift"},"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"role":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","title":"MBSCipherError.Code","abstract":[{"text":"Error codes for cipher operations","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}],"kind":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/invalidKey":{"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/invalidkey","type":"topic","kind":"symbol","role":"symbol","title":"invalidKey","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/invalidKey","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidKey"},{"kind":"text","text":": "},{"text":"MBSCipherError","kind":"typeIdentifier","preciseIdentifier":"s:SC14MBSCipherErrorLeV"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherError","text":"Code"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"role":"collection","type":"topic","kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS.","type":"text"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherError"}],"type":"topic","title":"MBSCipherError","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","op":"replace","value":"MBSCipherError"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBSCipherError"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherError"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle"}]}]}