{"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/keyDerivationFailed","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct"]]},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/keyderivationfailed"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"keyDerivationFailed","roleHeading":"Type Property","platforms":[{"deprecated":false,"introducedAt":"15.6","name":"iOS","unavailable":false,"beta":false},{"name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"15.6","unavailable":false},{"unavailable":false,"introducedAt":"15.6","beta":false,"deprecated":false,"name":"Mac Catalyst"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyDerivationFailed"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Code","preciseIdentifier":"c:@E@MBSCipherError"}],"role":"symbol","symbolKind":"property","modules":[{"name":"MbSecureCrypto"}],"externalID":"s:SC14MBSCipherErrorLeV19keyDerivationFailedSoAAVvpZ"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyDerivationFailed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MBSCipherError","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","preciseIdentifier":"s:SC14MBSCipherErrorLeV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherError","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","text":"Code"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"type":"topic","url":"\/documentation\/mbsecurecrypto","role":"collection","kind":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/keyDerivationFailed":{"role":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/keyderivationfailed","title":"keyDerivationFailed","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/keyDerivationFailed","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyDerivationFailed","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherError","text":"Code"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct":{"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","kind":"symbol","title":"MBSCipherError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"MBSCipherError","kind":"identifier"}],"navigatorTitle":[{"text":"MBSCipherError","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","title":"MBSCipherError.Code","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}],"role":"symbol","abstract":[{"type":"text","text":"Error codes for cipher operations"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","op":"replace","value":"MBSCipherError"},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherError"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","value":[{"text":"MBSCipherError","kind":"identifier"}]}]}]}