{"kind":"symbol","metadata":{"externalID":"s:SC14MBSCipherErrorLeV20unsupportedAlgorithmSoAAVvpZ","title":"unsupportedAlgorithm","modules":[{"name":"MbSecureCrypto"}],"role":"symbol","symbolKind":"property","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedAlgorithm","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SC14MBSCipherErrorLeV","kind":"typeIdentifier","text":"MBSCipherError"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherError","text":"Code"}],"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"15.6","name":"iOS"},{"unavailable":false,"beta":false,"introducedAt":"15.6","name":"iPadOS","deprecated":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"15.6","unavailable":false}]},"identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/unsupportedAlgorithm","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"unsupportedAlgorithm","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","preciseIdentifier":"s:SC14MBSCipherErrorLeV","kind":"typeIdentifier","text":"MBSCipherError"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherError","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","text":"Code"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/unsupportedalgorithm"]}],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct":{"kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherError","kind":"identifier"}],"navigatorTitle":[{"text":"MBSCipherError","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct","title":"MBSCipherError"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"kind":"symbol","url":"\/documentation\/mbsecurecrypto","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic","abstract":[{"text":"A secure cryptography library for iOS and macOS.","type":"text"}],"title":"MbSecureCrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/unsupportedAlgorithm":{"abstract":[],"title":"unsupportedAlgorithm","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedAlgorithm","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SC14MBSCipherErrorLeV","text":"MBSCipherError","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Code","preciseIdentifier":"c:@E@MBSCipherError"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/unsupportedalgorithm","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/unsupportedAlgorithm","type":"topic","role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Code","kind":"identifier"}],"title":"MBSCipherError.Code","role":"symbol","abstract":[{"text":"Error codes for cipher operations","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"MBSCipherError","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title"},{"value":[{"text":"MBSCipherError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments"},{"op":"replace","value":[{"text":"MBSCipherError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}