{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptString(_:key:algorithm:format:error:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decryptString"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"encryptedString","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"algorithm","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","text":"MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"format"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","text":"MBSCipherFormat","preciseIdentifier":"c:@E@MBSCipherFormat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?>?) -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptstring(_:key:algorithm:format:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptstring(_:key:algorithm:format:error:)"]}],"metadata":{"role":"symbol","roleHeading":"Type Method","modules":[{"name":"MbSecureCrypto"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptString","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"algorithm"},{"kind":"text","text":": "},{"text":"MBSCipherAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"text":"MBSCipherFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":"?>?) -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"decryptString(_:key:algorithm:format:error:)","externalID":"c:@M@MbSecureCrypto@objc(cs)MBSCipherBridge(cm)decryptString:key:algorithm:format:error:","navigatorTitle":[{"kind":"identifier","text":"decryptString:key:algorithm:format:error:"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/decryptString(_:key:algorithm:format:error:)":{"url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptstring(_:key:algorithm:format:error:)","role":"symbol","title":"decryptString(_:key:algorithm:format:error:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"decryptString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"algorithm","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","kind":"typeIdentifier","text":"MBSCipherAlgorithm"},{"kind":"text","text":", "},{"kind":"externalParam","text":"format"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherFormat","text":"MBSCipherFormat"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":"?>?) -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"text":"decryptString:key:algorithm:format:error:","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptString(_:key:algorithm:format:error:)","type":"topic","abstract":[]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","title":"MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"role":"collection","type":"topic","url":"\/documentation\/mbsecurecrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherFormat":{"title":"MBSCipherFormat","role":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","abstract":[{"text":"Supported ciphertext format versions","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherFormat"}],"type":"topic","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipherformat","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSCipherFormat"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"abstract":[],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","role":"symbol","title":"MBSCipherAlgorithm","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MBSCipherAlgorithm","kind":"identifier"}]},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge":{"url":"\/documentation\/mbsecurecrypto\/mbscipherbridge","role":"symbol","title":"MBSCipherBridge","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSCipherBridge"}],"kind":"symbol","navigatorTitle":[{"text":"MBSCipherBridge","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"decryptString:key:algorithm:format:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decryptString:key:algorithm:format:error:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"decryptString:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"encryptedString"},{"text":" ","kind":"text"},{"text":"key:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"key"},{"text":" ","kind":"text"},{"text":"algorithm:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","kind":"typeIdentifier","text":"MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"algorithm"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format:"},{"kind":"text","text":"("},{"text":"MBSCipherFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherFormat","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat"},{"text":") ","kind":"text"},{"text":"format","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"decryptString:key:algorithm:format:error:","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptString(_:key:algorithm:format:error:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"decryptString:key:algorithm:format:error:"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptString(_:key:algorithm:format:error:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/title","value":"MBSCipherFormat"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/fragments","value":[{"kind":"identifier","text":"MBSCipherFormat"}],"op":"replace"},{"value":[{"text":"MBSCipherFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","op":"replace","value":"MBSCipherAlgorithm"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/title","value":"MBSCipherBridge"},{"op":"replace","value":[{"kind":"identifier","text":"MBSCipherBridge"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/fragments"},{"value":[{"text":"MBSCipherBridge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/navigatorTitle","op":"replace"}]}]}