{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptData","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"algorithm","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","text":"MBSCipherAlgorithm","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"format","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MBSCipherFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?>?) -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"roleHeading":"Type Method","title":"decryptData(_:key:algorithm:format:error:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"decryptData:key:algorithm:format:error:"}],"modules":[{"name":"MbSecureCrypto"}],"externalID":"c:@M@MbSecureCrypto@objc(cs)MBSCipherBridge(cm)decryptData:key:algorithm:format:error:"},"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge"]]},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptdata(_:key:algorithm:format:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptdata(_:key:algorithm:format:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptData(_:key:algorithm:format:error:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decryptData"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"encryptedData"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"text":"algorithm","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","text":"MBSCipherAlgorithm","kind":"typeIdentifier","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"format"},{"text":": ","kind":"text"},{"text":"MBSCipherFormat","preciseIdentifier":"c:@E@MBSCipherFormat","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherFormat":{"title":"MBSCipherFormat","abstract":[{"type":"text","text":"Supported ciphertext format versions"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","type":"topic","navigatorTitle":[{"text":"MBSCipherFormat","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherFormat","kind":"identifier"}],"role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","type":"topic","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","role":"collection","kind":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge":{"title":"MBSCipherBridge","abstract":[],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge","type":"topic","navigatorTitle":[{"text":"MBSCipherBridge","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherbridge","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherBridge","kind":"identifier"}],"role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/decryptData(_:key:algorithm:format:error:)":{"abstract":[],"title":"decryptData(_:key:algorithm:format:error:)","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptData(_:key:algorithm:format:error:)","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptdata(_:key:algorithm:format:error:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"algorithm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm","text":"MBSCipherAlgorithm"},{"text":", ","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBSCipherFormat","text":"MBSCipherFormat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":"?>?) -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"decryptData:key:algorithm:format:error:","kind":"identifier"}],"kind":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"identifier"}],"title":"MBSCipherAlgorithm","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"decryptData:key:algorithm:format:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decryptData:key:algorithm:format:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"decryptData:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"encryptedData"},{"text":" ","kind":"text"},{"text":"key:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"key","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"algorithm:"},{"kind":"text","text":"("},{"text":"MBSCipherAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm"},{"text":") ","kind":"text"},{"text":"algorithm","kind":"internalParam"},{"kind":"text","text":" "},{"text":"format:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MBSCipherFormat","preciseIdentifier":"c:@E@MBSCipherFormat","kind":"typeIdentifier","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat"},{"text":") ","kind":"text"},{"text":"format","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/title","value":"MBSCipherFormat"},{"value":[{"kind":"identifier","text":"MBSCipherFormat"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherFormat"}]},{"value":"MBSCipherBridge","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/title","op":"replace"},{"op":"replace","value":[{"text":"MBSCipherBridge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/fragments"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/navigatorTitle","op":"replace","value":[{"text":"MBSCipherBridge","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptData(_:key:algorithm:format:error:)\/title","value":"decryptData:key:algorithm:format:error:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"decryptData:key:algorithm:format:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptData(_:key:algorithm:format:error:)\/fragments"},{"op":"replace","value":"MBSCipherAlgorithm","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}]}]}]}