{"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge"]]},"metadata":{"role":"symbol","title":"decryptString(_:key:algorithm:error:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"decryptString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"algorithm","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","kind":"typeIdentifier","text":"MBSCipherAlgorithm"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":"?>?) -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"externalID":"c:@M@MbSecureCrypto@objc(cs)MBSCipherBridge(cm)decryptString:key:algorithm:error:","roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"MbSecureCrypto"}],"navigatorTitle":[{"text":"decryptString:key:algorithm:error:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decryptString"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"encryptedString"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":", ","kind":"text"},{"text":"algorithm","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MBSCipherAlgorithm","kind":"typeIdentifier","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?>?) -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptString(_:key:algorithm:error:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptstring(_:key:algorithm:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptstring(_:key:algorithm:error:)"]}],"sections":[],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"role":"collection","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"type":"topic","kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"kind":"symbol","navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","type":"topic","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"identifier"}],"abstract":[],"title":"MBSCipherAlgorithm","role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge":{"abstract":[],"role":"symbol","kind":"symbol","title":"MBSCipherBridge","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherBridge","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MBSCipherBridge","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherbridge"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSCipherBridge/decryptString(_:key:algorithm:error:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"algorithm","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MBSCipherAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"decryptString:key:algorithm:error:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/decryptString(_:key:algorithm:error:)","role":"symbol","abstract":[],"url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/decryptstring(_:key:algorithm:error:)","title":"decryptString(_:key:algorithm:error:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"decryptString:key:algorithm:error:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"decryptString:key:algorithm:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"decryptString:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"encryptedString"},{"text":" ","kind":"text"},{"text":"key:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"algorithm:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"MBSCipherAlgorithm","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"kind":"text","text":") "},{"text":"algorithm","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","value":"MBSCipherAlgorithm","op":"replace"},{"op":"replace","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"op":"replace"},{"value":"MBSCipherBridge","op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/title"},{"value":[{"kind":"identifier","text":"MBSCipherBridge"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/fragments"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherBridge"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptString(_:key:algorithm:error:)\/title","value":"decryptString:key:algorithm:error:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"decryptString:key:algorithm:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1decryptString(_:key:algorithm:error:)\/fragments"}]}]}