{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptData"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"text":"algorithm","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","kind":"typeIdentifier","text":"MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"kind":"text","text":", "},{"text":"format","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherFormat","text":"MBSCipherFormat"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?>?) -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"externalID":"c:@M@MbSecureCrypto@objc(cs)MBSCipherBridge(cm)encryptData:key:algorithm:format:error:","symbolKind":"method","modules":[{"name":"MbSecureCrypto"}],"roleHeading":"Type Method","title":"encryptData(_:key:algorithm:format:error:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"encryptData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"algorithm","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MBSCipherAlgorithm","preciseIdentifier":"c:@E@MBSCipherAlgorithm","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBSCipherFormat","text":"MBSCipherFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":"?>?) -> "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"encryptData:key:algorithm:format:error:"}],"role":"symbol"},"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptData(_:key:algorithm:format:error:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptdata(_:key:algorithm:format:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptdata(_:key:algorithm:format:error:)"]}],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherBridge":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSCipherBridge"}],"type":"topic","navigatorTitle":[{"text":"MBSCipherBridge","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherbridge","title":"MBSCipherBridge","kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge","abstract":[{"text":"Internal use only","type":"text"}],"role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"title":"MBSCipherAlgorithm","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBSCipherAlgorithm","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"kind":"symbol","abstract":[{"text":"Supported Cipher Algorithms","type":"text"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"url":"\/documentation\/mbsecurecrypto","title":"MbSecureCrypto","kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat":{"type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","kind":"symbol","role":"symbol","abstract":[{"text":"Supported ciphertext format versions","type":"text"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat","navigatorTitle":[{"kind":"identifier","text":"MBSCipherFormat"}],"title":"MBSCipherFormat","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBSCipherFormat","kind":"identifier"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherBridge/encryptData(_:key:algorithm:format:error:)":{"title":"encryptData(_:key:algorithm:format:error:)","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptData(_:key:algorithm:format:error:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encryptData","kind":"identifier"},{"kind":"text","text":"("},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"algorithm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","text":"MBSCipherAlgorithm","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"format","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MBSCipherFormat","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherFormat"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?>?) -> "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[],"navigatorTitle":[{"text":"encryptData:key:algorithm:format:error:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptdata(_:key:algorithm:format:error:)","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"encryptData:key:algorithm:format:error:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"encryptData:key:algorithm:format:error:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"encryptData:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"data","kind":"internalParam"},{"kind":"text","text":" "},{"text":"key:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"key"},{"text":" ","kind":"text"},{"text":"algorithm:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","kind":"typeIdentifier","text":"MBSCipherAlgorithm","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"algorithm"},{"kind":"text","text":" "},{"text":"format:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","text":"MBSCipherFormat","preciseIdentifier":"c:@E@MBSCipherFormat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"format","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/title","op":"replace","value":"MBSCipherBridge"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/fragments","value":[{"text":"MBSCipherBridge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/navigatorTitle","value":[{"text":"MBSCipherBridge","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","value":"MBSCipherAlgorithm"},{"value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","value":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/title","value":"MBSCipherFormat","op":"replace"},{"value":[{"text":"MBSCipherFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/fragments"},{"value":[{"kind":"identifier","text":"MBSCipherFormat"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptData(_:key:algorithm:format:error:)\/title","value":"encryptData:key:algorithm:format:error:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"encryptData:key:algorithm:format:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptData(_:key:algorithm:format:error:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}