{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptData(_:key:algorithm:error:)"},"metadata":{"navigatorTitle":[{"text":"encryptData:key:algorithm:error:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"MbSecureCrypto"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encryptData"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"algorithm"},{"text":": ","kind":"text"},{"text":"MBSCipherAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?>?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?"}],"roleHeading":"Type Method","role":"symbol","externalID":"c:@M@MbSecureCrypto@objc(cs)MBSCipherBridge(cm)encryptData:key:algorithm:error:","title":"encryptData(_:key:algorithm:error:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptdata(_:key:algorithm:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptdata(_:key:algorithm:error:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptData"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"algorithm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","text":"MBSCipherAlgorithm","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?>?) -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherBridge/encryptData(_:key:algorithm:error:)":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/encryptData(_:key:algorithm:error:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encryptData","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"algorithm","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MBSCipherAlgorithm","kind":"typeIdentifier","text":"MBSCipherAlgorithm"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":"?>?) -> "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[],"navigatorTitle":[{"text":"encryptData:key:algorithm:error:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"encryptData(_:key:algorithm:error:)","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/encryptdata(_:key:algorithm:error:)"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherBridge":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSCipherBridge"}],"navigatorTitle":[{"text":"MBSCipherBridge","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Internal use only","type":"text"}],"type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge","role":"symbol","title":"MBSCipherBridge","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherAlgorithm":{"type":"topic","navigatorTitle":[{"text":"MBSCipherAlgorithm","kind":"identifier"}],"kind":"symbol","title":"MBSCipherAlgorithm","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MBSCipherAlgorithm"}],"url":"\/documentation\/mbsecurecrypto\/mbscipheralgorithm","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm","abstract":[{"text":"Supported Cipher Algorithms","type":"text"}],"role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","role":"collection","type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"encryptData:key:algorithm:error:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"encryptData:key:algorithm:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"encryptData:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"key:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"text":"algorithm:","kind":"identifier"},{"kind":"text","text":"("},{"text":"MBSCipherAlgorithm","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSCipherAlgorithm","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherAlgorithm"},{"text":") ","kind":"text"},{"text":"algorithm","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptData(_:key:algorithm:error:)\/title","value":"encryptData:key:algorithm:error:"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge~1encryptData(_:key:algorithm:error:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"encryptData:key:algorithm:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/title","value":"MBSCipherBridge"},{"value":[{"text":"MBSCipherBridge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherBridge"}]},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/title","value":"MBSCipherAlgorithm","op":"replace"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}]},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherAlgorithm\/navigatorTitle","value":[{"kind":"identifier","text":"MBSCipherAlgorithm"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}