{"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipherbridge\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/init"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge"]]},"metadata":{"symbolKind":"method","modules":[{"name":"MbSecureCrypto"}],"externalID":"c:@M@MbSecureCrypto@objc(cs)MBSCipherBridge(im)init","title":"init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}]},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","kind":"symbol","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"role":"collection","url":"\/documentation\/mbsecurecrypto","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","type":"topic"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherBridge/init":{"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbscipherbridge\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge\/init","kind":"symbol","role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherBridge":{"navigatorTitle":[{"text":"MBSCipherBridge","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherbridge","kind":"symbol","title":"MBSCipherBridge","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherBridge","kind":"identifier"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherBridge","type":"topic","abstract":[{"text":"Internal use only","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBSCipherBridge","op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/title"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/fragments","value":[{"text":"MBSCipherBridge","kind":"identifier"}]},{"value":[{"text":"MBSCipherBridge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherBridge\/navigatorTitle"}]}]}