{"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto"]]},"abstract":[{"type":"text","text":"Error codes for Random operations."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code"]},{"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"],"anchor":"Error-Handling","generated":true,"title":"Error Handling"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/bufferAllocation","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/generationFailed","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/invalidByteCount"],"anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/Equatable-Implementations","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/MbSecureCrypto\/s15BitwiseCopyableP","doc:\/\/MbSecureCrypto\/SQ","doc:\/\/MbSecureCrypto\/SH","doc:\/\/MbSecureCrypto\/SY","doc:\/\/MbSecureCrypto\/s8SendableP"],"title":"Conforms To"}],"metadata":{"platforms":[{"name":"iOS","introducedAt":"15.6","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"15.6","beta":false},{"introducedAt":"15.6","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false}],"symbolKind":"enum","role":"symbol","title":"MBSRandomError.Code","roleHeading":"Enumeration","navigatorTitle":[{"text":"Code","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"externalID":"c:@E@MBSRandomError","modules":[{"name":"MbSecureCrypto"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/Equatable-Implementations":{"abstract":[],"type":"topic","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/equatable-implementations","kind":"article","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/Equatable-Implementations"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherError-swift.struct/Code":{"title":"MBSCipherError.Code","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Code"}],"abstract":[{"type":"text","text":"Error codes for cipher operations"}],"url":"\/documentation\/mbsecurecrypto\/mbsciphererror-swift.struct\/code"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/RawRepresentable-Implementations":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/RawRepresentable-Implementations","kind":"article","abstract":[],"role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/rawrepresentable-implementations"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/bufferAllocation":{"abstract":[],"type":"topic","role":"symbol","title":"MBSRandomError.Code.bufferAllocation","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/bufferallocation","navigatorTitle":[{"text":"MBSRandomErrorBufferAllocation","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferAllocation"}],"kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/bufferAllocation"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/invalidByteCount":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/invalidByteCount","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MBSRandomErrorInvalidByteCount","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidByteCount","kind":"identifier"}],"title":"MBSRandomError.Code.invalidByteCount","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/invalidbytecount"},"doc://MbSecureCrypto/SQ":{"type":"unresolvable","identifier":"doc:\/\/MbSecureCrypto\/SQ","title":"Swift.Equatable"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/generationFailed":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/generationFailed","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MBSRandomErrorGenerationFailed","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"generationFailed"}],"title":"MBSRandomError.Code.generationFailed","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/generationfailed"},"doc://MbSecureCrypto/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/MbSecureCrypto\/s8SendableP"},"doc://MbSecureCrypto/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/MbSecureCrypto\/SY"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","type":"topic","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}],"title":"MbSecureCrypto","kind":"symbol","url":"\/documentation\/mbsecurecrypto","role":"collection"},"doc://MbSecureCrypto/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/MbSecureCrypto\/SH"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"abstract":[{"type":"text","text":"Error codes for Random operations."}],"title":"MBSRandomError.Code","navigatorTitle":[{"kind":"identifier","text":"Code"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code/init(rawValue:)":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/init(rawValue:)","kind":"symbol","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"title":"init(rawValue:)","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code\/init(rawvalue:)"},"doc://MbSecureCrypto/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","identifier":"doc:\/\/MbSecureCrypto\/s15BitwiseCopyableP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"15.6","beta":false},{"name":"iPadOS","introducedAt":"15.6","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"15.6","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"MBSRandomError","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MBSRandomError","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MBSRandomError","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/bufferAllocation","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/generationFailed","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code\/invalidByteCount"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Error Handling","generated":true,"anchor":"Error-Handling","identifiers":["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherError-swift.struct\/Code"]}]},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBSRandomError","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/title","value":"MBSCipherError"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/fragments","op":"replace","value":[{"text":"MBSCipherError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherError-swift.struct~1Code\/navigatorTitle","value":[{"text":"MBSCipherError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1bufferAllocation\/title","value":"MBSRandomErrorBufferAllocation"},{"value":[{"kind":"identifier","text":"MBSRandomErrorBufferAllocation"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1bufferAllocation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1invalidByteCount\/title","value":"MBSRandomErrorInvalidByteCount"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1invalidByteCount\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBSRandomErrorInvalidByteCount"}]},{"op":"replace","value":"MBSRandomErrorGenerationFailed","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1generationFailed\/title"},{"value":[{"text":"MBSRandomErrorGenerationFailed","kind":"identifier"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code~1generationFailed\/fragments","op":"replace"},{"op":"replace","value":"MBSRandomError","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MBSRandomError"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle","value":[{"kind":"identifier","text":"MBSRandomError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}