{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/generationFailed"},"metadata":{"platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"15.6","beta":false},{"introducedAt":"15.6","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"beta":false,"introducedAt":"15.6","deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"title":"generationFailed","externalID":"s:SC14MBSRandomErrorLeV16generationFailedSoAAVvpZ","modules":[{"name":"MbSecureCrypto"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"generationFailed","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MBSRandomError","preciseIdentifier":"s:SC14MBSRandomErrorLeV"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Code","preciseIdentifier":"c:@E@MBSRandomError"}],"roleHeading":"Type Property","role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/generationfailed"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generationFailed"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct","preciseIdentifier":"s:SC14MBSRandomErrorLeV","text":"MBSRandomError","kind":"typeIdentifier"},{"kind":"text","text":"."},{"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","kind":"typeIdentifier","text":"Code","preciseIdentifier":"c:@E@MBSRandomError"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","kind":"symbol","type":"topic","navigatorTitle":[{"text":"Code","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","abstract":[{"text":"Error codes for Random operations.","type":"text"}],"title":"MBSRandomError.Code","role":"symbol"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto":{"role":"collection","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS."}],"type":"topic","kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/generationFailed":{"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/generationfailed","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"generationFailed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MBSRandomError","kind":"typeIdentifier","preciseIdentifier":"s:SC14MBSRandomErrorLeV"},{"text":".","kind":"text"},{"text":"Code","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSRandomError"}],"title":"generationFailed","identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/generationFailed"},"doc://com.mavbozo.mbsecurecrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct":{"url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MBSRandomError"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBSRandomError"}],"abstract":[],"identifier":"doc:\/\/com.mavbozo.mbsecurecrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct","title":"MBSRandomError","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBSRandomError","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MBSRandomError"}]},{"value":[{"kind":"identifier","text":"MBSRandomError"}],"op":"replace","path":"\/references\/doc:~1~1com.mavbozo.mbsecurecrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}