{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidByteCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct","text":"MBSRandomError","preciseIdentifier":"s:SC14MBSRandomErrorLeV"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSRandomError","text":"Code","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/invalidByteCount","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/invalidbytecount"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct"]]},"metadata":{"externalID":"s:SC14MBSRandomErrorLeV16invalidByteCountSoAAVvpZ","symbolKind":"property","modules":[{"name":"MbSecureCrypto"}],"roleHeading":"Type Property","title":"invalidByteCount","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"invalidByteCount","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MBSRandomError","preciseIdentifier":"s:SC14MBSRandomErrorLeV"},{"kind":"text","text":"."},{"text":"Code","kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSRandomError"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS","introducedAt":"15.6"},{"unavailable":false,"name":"iPadOS","introducedAt":"15.6","deprecated":false,"beta":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"15.6","unavailable":false,"beta":false}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/invalidByteCount":{"abstract":[],"url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/invalidbytecount","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidByteCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MBSRandomError","preciseIdentifier":"s:SC14MBSRandomErrorLeV"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MBSRandomError","text":"Code"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/invalidByteCount","title":"invalidByteCount"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct/Code":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Code"}],"navigatorTitle":[{"text":"Code","kind":"identifier"}],"abstract":[{"type":"text","text":"Error codes for Random operations."}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct\/Code","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct\/code","kind":"symbol","title":"MBSRandomError.Code"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSRandomError-swift.struct":{"abstract":[],"type":"topic","role":"symbol","title":"MBSRandomError","navigatorTitle":[{"text":"MBSRandomError","kind":"identifier"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSRandomError-swift.struct","url":"\/documentation\/mbsecurecrypto\/mbsrandomerror-swift.struct","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MBSRandomError"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","kind":"symbol","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"role":"collection","url":"\/documentation\/mbsecurecrypto","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBSRandomError","op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/title"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"MBSRandomError"}],"op":"replace"},{"value":[{"text":"MBSRandomError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSRandomError-swift.struct~1Code\/navigatorTitle"}]}]}