name: Generate and Deploy DocC

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.0
        run: |
          sudo xcode-select -s /Applications/Xcode_16.0.app
          xcodebuild -version

      - name: List Available Destinations
        run: xcodebuild -scheme MbSecureCrypto -showdestinations

      - name: Build DocC
        run: |
          xcodebuild docbuild \
            -scheme MbSecureCrypto \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath build \
            -verbose

          $(xcrun --find docc) process-archive \
            transform-for-static-hosting build/Build/Products/Debug-iphonesimulator/MbSecureCrypto.doccarchive \
            --hosting-base-path MbSecureCrypto \
            --output-path docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ./docs
