{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/Equatable-Implementations"]]},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipherformat\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]}],"metadata":{"symbolKind":"op","modules":[{"relatedModules":["Swift"],"name":"MbSecureCrypto"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@E@MBSCipherFormat","extendedModule":"Swift","title":"!=(_:_:)","roleHeading":"Operator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol"},"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/!=(_:_:)","interfaceLanguage":"swift"},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat/!=(_:_:)":{"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/!=(_:_:)","abstract":[],"kind":"symbol","title":"!=(_:_:)","type":"topic","url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat":{"type":"topic","navigatorTitle":[{"text":"MBSCipherFormat","kind":"identifier"}],"kind":"symbol","title":"MBSCipherFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBSCipherFormat","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","abstract":[{"text":"Supported ciphertext format versions","type":"text"}],"role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","role":"collection","type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat/Equatable-Implementations":{"kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","value":"MBSCipherFormat","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/fragments","value":[{"text":"MBSCipherFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/navigatorTitle","value":[{"text":"MBSCipherFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}