{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherformat\/hash(into:)"]}],"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/hash(into:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"metadata":{"title":"hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"Swift","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@E@MBSCipherFormat","role":"symbol","roleHeading":"Instance Method","modules":[{"relatedModules":["Swift"],"name":"MbSecureCrypto"}],"symbolKind":"method","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]}},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/RawRepresentable-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"kind":"text","text":" "},{"text":"hasher","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"title":"MbSecureCrypto","kind":"symbol","abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"role":"collection","url":"\/documentation\/mbsecurecrypto","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","type":"topic"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat/hash(into:)":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/hash(into:)","title":"hash(into:)","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/hash(into:)","abstract":[],"role":"symbol","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]}},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MBSCipherFormat","kind":"identifier"}],"navigatorTitle":[{"text":"MBSCipherFormat","kind":"identifier"}],"type":"topic","abstract":[{"text":"Supported ciphertext format versions","type":"text"}],"role":"symbol","title":"MBSCipherFormat","kind":"symbol","url":"\/documentation\/mbsecurecrypto\/mbscipherformat","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat/RawRepresentable-Implementations":{"abstract":[],"type":"topic","title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/RawRepresentable-Implementations","url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/rawrepresentable-implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBSCipherFormat","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/title"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/fragments","op":"replace","value":[{"text":"MBSCipherFormat","kind":"identifier"}]},{"op":"replace","value":[{"text":"MBSCipherFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/navigatorTitle"}]}]}