{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat"]]},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipherformat\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"collectionGroup","modules":[{"name":"MbSecureCrypto"}],"roleHeading":"API Collection","title":"RawRepresentable Implementations"},"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/hashValue"],"anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/hash(into:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat/hash(into:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/hash(into:)","role":"symbol","title":"hash(into:)","url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/hash(into:)"},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"kind":"symbol","title":"MbSecureCrypto","url":"\/documentation\/mbsecurecrypto","role":"collection","type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","abstract":[{"text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities.","type":"text"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat/hashValue":{"type":"topic","kind":"symbol","title":"hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/hashvalue","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/hashValue","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"abstract":[],"role":"symbol"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat":{"type":"topic","navigatorTitle":[{"text":"MBSCipherFormat","kind":"identifier"}],"kind":"symbol","title":"MBSCipherFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MBSCipherFormat","kind":"identifier"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","abstract":[{"text":"Supported ciphertext format versions","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MBSCipherFormat","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/fragments","value":[{"text":"MBSCipherFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBSCipherFormat"}]}]}]}