{"metadata":{"title":"MBSCipherFormat.V0","navigatorTitle":[{"kind":"identifier","text":"MBSCipherFormatV0"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"V0","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"MbSecureCrypto"}],"symbolKind":"case","role":"symbol","platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"15.6","unavailable":false},{"beta":false,"introducedAt":"15.6","name":"iPadOS","unavailable":false,"deprecated":false},{"deprecated":false,"introducedAt":"15.6","beta":false,"name":"Mac Catalyst","unavailable":false}],"externalID":"c:@E@MBSCipherFormat@MBSCipherFormatV0"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Format V0: [12B nonce][ciphertext][16B tag]"},{"text":" ","type":"text"},{"type":"text","text":"12 bytes nonce"},{"type":"text","text":" "},{"type":"text","text":"16 bytes tag"}],"hierarchy":{"paths":[["doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat"]]},"variants":[{"paths":["\/documentation\/mbsecurecrypto\/mbscipherformat\/v0"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mbsecurecrypto\/mbscipherformat\/v0"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"V0"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/V0","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat/V0":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Format V0: [12B nonce][ciphertext][16B tag]"},{"text":" ","type":"text"},{"type":"text","text":"12 bytes nonce"},{"text":" ","type":"text"},{"type":"text","text":"16 bytes tag"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat\/v0","navigatorTitle":[{"kind":"identifier","text":"MBSCipherFormatV0"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"V0"}],"identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat\/V0","title":"MBSCipherFormat.V0"},"doc://MbSecureCrypto/documentation/MbSecureCrypto/MBSCipherFormat":{"type":"topic","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto\/MBSCipherFormat","kind":"symbol","role":"symbol","abstract":[{"text":"Supported ciphertext format versions","type":"text"}],"url":"\/documentation\/mbsecurecrypto\/mbscipherformat","navigatorTitle":[{"kind":"identifier","text":"MBSCipherFormat"}],"title":"MBSCipherFormat","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MBSCipherFormat","kind":"identifier"}]},"doc://MbSecureCrypto/documentation/MbSecureCrypto":{"abstract":[{"type":"text","text":"A secure cryptography library for iOS and macOS that provides cryptographically secure random number generation and encryption capabilities."}],"url":"\/documentation\/mbsecurecrypto","title":"MbSecureCrypto","kind":"symbol","identifier":"doc:\/\/MbSecureCrypto\/documentation\/MbSecureCrypto","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"MBSCipherFormatV0","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MBSCipherFormatV0"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"MBSCipherFormatV0","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"MBSCipherFormatV0","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat~1V0\/title","op":"replace"},{"op":"replace","value":[{"text":"MBSCipherFormatV0","kind":"identifier"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat~1V0\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/title","value":"MBSCipherFormat"},{"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/fragments","value":[{"kind":"identifier","text":"MBSCipherFormat"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MBSCipherFormat"}],"path":"\/references\/doc:~1~1MbSecureCrypto~1documentation~1MbSecureCrypto~1MBSCipherFormat\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}